"""Tests for MCP Interface (SAP-043)

Tests verify FastMCP server setup and configuration for GitHub operations.

Note: Comprehensive tool testing requires refactoring tools to be importable
(currently defined as nested functions). This provides baseline validation.

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (8 tools, 3 resources)
"""

import json
import os
import pytest
from unittest.mock import patch, Mock

from chora_github.core.exceptions import (
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
    GithubValidationError,
)


# ============================================================================
# Test MCP Server Setup
# ============================================================================


class TestMCPServerCreation:
    """Test MCP server creation and configuration."""

    def test_create_mcp_server(self):
        """Test that MCP server can be created successfully."""
        from chora_github.interfaces.mcp import create_mcp_server

        mcp = create_mcp_server()

        assert mcp is not None
        assert mcp.name == "mcp-server-github"
        # Note: FastMCP doesn't expose version/description attributes

    def test_server_metadata(self):
        """Test server metadata is configured correctly."""
        from chora_github.interfaces.mcp import create_mcp_server

        # Verify server creation with correct parameters
        mcp = create_mcp_server()

        # Server should have name
        assert hasattr(mcp, "name")
        assert mcp.name == "mcp-server-github"

    def test_server_registers_tools(self):
        """Test that register_tools is called during server creation."""
        from chora_github.interfaces.mcp import create_mcp_server

        # Server creation should not raise errors
        mcp = create_mcp_server()
        assert mcp is not None

    def test_server_registers_resources(self):
        """Test that register_resources is called during server creation."""
        from chora_github.interfaces.mcp import create_mcp_server

        # Server creation should not raise errors
        mcp = create_mcp_server()
        assert mcp is not None


# ============================================================================
# Test Helper Functions
# ============================================================================


class TestHelperFunctions:
    """Test tool helper functions."""

    def test_make_tool_name(self):
        """Test tool name namespace formatting."""
        from chora_github.interfaces.mcp.tools import make_tool_name

        assert make_tool_name("list_issues") == "github:list_issues"
        assert make_tool_name("create_issue") == "github:create_issue"

    def test_make_resource_uri(self):
        """Test resource URI namespace formatting."""
        from chora_github.interfaces.mcp.resources import make_resource_uri

        uri = make_resource_uri("repo", "octocat", "Hello-World", "issues")
        assert uri == "github://repo/octocat/Hello-World/issues"

    def test_get_service_requires_token(self):
        """Test _get_service raises ValueError when no token available."""
        from chora_github.interfaces.mcp.tools import _get_service

        # Clear GITHUB_TOKEN env var for this test
        with patch.dict(os.environ, {}, clear=True):
            with pytest.raises(ValueError, match="GitHub token required"):
                _get_service(token=None)

    def test_get_service_uses_provided_token(self):
        """Test _get_service uses provided token parameter."""
        from chora_github.interfaces.mcp.tools import _get_service

        service = _get_service(token="ghp_test_token")
        assert service is not None
        assert service.token == "ghp_test_token"

    def test_get_service_uses_env_token(self):
        """Test _get_service falls back to GITHUB_TOKEN environment variable."""
        from chora_github.interfaces.mcp.tools import _get_service

        with patch.dict(os.environ, {"GITHUB_TOKEN": "ghp_env_token"}):
            service = _get_service(token=None)
            assert service is not None
            assert service.token == "ghp_env_token"


# ============================================================================
# Test Data Models (Fixtures)
# ============================================================================


class TestDataModels:
    """Test that test fixtures create valid data models."""

    def test_issue_data_fixture(self, issue):
        """Test IssueData fixture creates valid model."""
        assert issue.number == 1
        assert issue.title == "Test Issue"
        assert issue.state == "open"
        assert issue.url == "https://github.com/octocat/Hello-World/issues/1"
        assert "bug" in issue.labels
        assert "octocat" in issue.assignees

    def test_pr_data_fixture(self, pr):
        """Test PRData fixture creates valid model."""
        assert pr.number == 1
        assert pr.title == "Test Pull Request"
        assert pr.state == "open"
        assert pr.url == "https://github.com/octocat/Hello-World/pull/1"
        assert pr.head_ref == "feature-branch"
        assert pr.base_ref == "main"

    def test_file_data_fixture(self, file_data):
        """Test FileData fixture creates valid model."""
        assert file_data.name == "README.md"
        assert file_data.path == "README.md"
        assert file_data.type == "file"
        assert file_data.size == 1024

    def test_multiple_issues_fixture(self, multiple_issues):
        """Test multiple_issues fixture creates list of valid models."""
        assert len(multiple_issues) == 5
        assert all(hasattr(issue, "number") for issue in multiple_issues)
        assert multiple_issues[0].number == 1
        assert multiple_issues[4].number == 5

    def test_multiple_prs_fixture(self, multiple_prs):
        """Test multiple_prs fixture creates list of valid models."""
        assert len(multiple_prs) == 3
        assert all(hasattr(pr, "number") for pr in multiple_prs)

    def test_multiple_files_fixture(self, multiple_files):
        """Test multiple_files fixture creates list of valid models."""
        assert len(multiple_files) == 4
        assert multiple_files[0].name == "README.md"


# ============================================================================
# Test Mock Service
# ============================================================================


class TestMockGithubService:
    """Test that mock GitHub service is properly configured."""

    def test_mock_service_list_issues(self, mock_github_service):
        """Test mock service returns valid ListIssuesResponse."""
        from chora_github.core.models import ListIssuesRequest

        request = ListIssuesRequest(repo="octocat/Hello-World")
        response = mock_github_service.list_issues(request)

        assert response.total_count == 1
        assert len(response.issues) == 1
        assert response.issues[0].number == 1

    def test_mock_service_create_issue(self, mock_github_service):
        """Test mock service returns valid CreateIssueResponse."""
        from chora_github.core.models import CreateIssueRequest

        request = CreateIssueRequest(
            repo="octocat/Hello-World",
            title="Test",
            body="Body",
        )
        response = mock_github_service.create_issue(request)

        assert response.issue.number == 1

    def test_mock_service_get_issue(self, mock_github_service):
        """Test mock service returns valid GetIssueResponse."""
        from chora_github.core.models import GetIssueRequest

        request = GetIssueRequest(repo="octocat/Hello-World", issue_number=1)
        response = mock_github_service.get_issue(request)

        assert response.issue.number == 1

    def test_mock_service_get_issue_not_found(self, mock_github_service):
        """Test mock service raises GithubNotFoundError for invalid issue."""
        from chora_github.core.models import GetIssueRequest

        request = GetIssueRequest(repo="octocat/Hello-World", issue_number=999)

        with pytest.raises(GithubNotFoundError):
            mock_github_service.get_issue(request)

    def test_mock_service_list_prs(self, mock_github_service):
        """Test mock service returns valid ListPRsResponse."""
        from chora_github.core.models import ListPRsRequest

        request = ListPRsRequest(repo="octocat/Hello-World")
        response = mock_github_service.list_prs(request)

        assert response.total_count == 1
        assert len(response.pull_requests) == 1

    def test_mock_service_get_file_contents(self, mock_github_service):
        """Test mock service returns valid GetFileContentsResponse."""
        from chora_github.core.models import GetFileContentsRequest

        request = GetFileContentsRequest(repo="octocat/Hello-World", path="README.md")
        response = mock_github_service.get_file_contents(request)

        assert response.path == "README.md"
        assert "Hello World" in response.content


# ============================================================================
# Test Resource Examples
# ============================================================================


class TestResourceExamples:
    """Test resource URI examples are valid."""

    def test_resource_examples_defined(self):
        """Test RESOURCE_EXAMPLES is defined and has correct structure."""
        from chora_github.interfaces.mcp.resources import RESOURCE_EXAMPLES

        assert len(RESOURCE_EXAMPLES) == 3
        assert all("uri" in example for example in RESOURCE_EXAMPLES)
        assert all("description" in example for example in RESOURCE_EXAMPLES)

    def test_resource_example_issues(self):
        """Test issues resource example."""
        from chora_github.interfaces.mcp.resources import RESOURCE_EXAMPLES

        issues_example = next(
            ex for ex in RESOURCE_EXAMPLES if "issues" in ex["uri"]
        )
        assert issues_example["uri"] == "github://repo/octocat/Hello-World/issues"

    def test_resource_example_prs(self):
        """Test PRs resource example."""
        from chora_github.interfaces.mcp.resources import RESOURCE_EXAMPLES

        prs_example = next(ex for ex in RESOURCE_EXAMPLES if "prs" in ex["uri"])
        assert prs_example["uri"] == "github://repo/octocat/Hello-World/prs"

    def test_resource_example_files(self):
        """Test files resource example."""
        from chora_github.interfaces.mcp.resources import RESOURCE_EXAMPLES

        files_example = next(ex for ex in RESOURCE_EXAMPLES if "files" in ex["uri"])
        assert files_example["uri"] == "github://repo/octocat/Hello-World/files"


# ============================================================================
# Test Tool Examples
# ============================================================================


class TestToolExamples:
    """Test tool URI examples are valid."""

    def test_tool_examples_defined(self):
        """Test TOOL_EXAMPLES is defined and has correct structure."""
        from chora_github.interfaces.mcp.tools import TOOL_EXAMPLES

        assert len(TOOL_EXAMPLES) >= 8  # At least 8 tools
        assert all("tool" in example for example in TOOL_EXAMPLES)
        assert all("description" in example for example in TOOL_EXAMPLES)

    def test_tool_example_list_issues(self):
        """Test list_issues tool example."""
        from chora_github.interfaces.mcp.tools import TOOL_EXAMPLES

        list_issues_example = next(
            ex for ex in TOOL_EXAMPLES if ex["tool"] == "github:list_issues"
        )
        assert "List issues" in list_issues_example["description"]

    def test_tool_example_create_issue(self):
        """Test create_issue tool example."""
        from chora_github.interfaces.mcp.tools import TOOL_EXAMPLES

        create_issue_example = next(
            ex for ex in TOOL_EXAMPLES if ex["tool"] == "github:create_issue"
        )
        assert "Create" in create_issue_example["description"]


# ============================================================================
# Integration Tests (End-to-End)
# ============================================================================


class TestMCPIntegration:
    """Integration tests for MCP server."""

    def test_mcp_server_creation_no_pytest(self):
        """Test MCP server is NOT created during pytest runs."""
        # Server should be None when PYTEST_CURRENT_TEST is set
        with patch.dict(os.environ, {"PYTEST_CURRENT_TEST": "test"}):
            # Re-import to trigger module-level check
            import importlib
            from chora_github.interfaces import mcp as mcp_module

            importlib.reload(mcp_module)

            # In test mode, mcp should be None
            assert mcp_module.mcp is None

    def test_mcp_server_creation_normal_mode(self):
        """Test MCP server IS created in normal (non-test) mode."""
        # Clear PYTEST_CURRENT_TEST to simulate normal mode
        with patch.dict(os.environ, {}, clear=True):
            # Re-import to trigger module-level check
            import importlib
            from chora_github.interfaces import mcp as mcp_module

            importlib.reload(mcp_module)

            # In normal mode, mcp should be created
            assert mcp_module.mcp is not None
            assert mcp_module.mcp.name == "mcp-server-github"
