"""Tests for GitHub REST API Interface (SAP-043)

Tests verify REST API endpoints, request/response handling, error
responses, and HTTP status codes.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from github.interfaces.rest import app


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def client():
    """Create test client."""
    return TestClient(app)


@pytest.fixture
def sample_entity_data():
    """Sample entity data for testing."""
    return {
        "name": "Test Entity",
        "description": "Test description",
        "metadata": {"key": "value"},
    }


# ============================================================================
# Test Root Endpoints
# ============================================================================


class TestRootEndpoints:
    """Test root and meta endpoints."""

    def test_root_endpoint(self, client):
        """Test root endpoint returns API info."""
        response = client.get("/")

        assert response.status_code == 200
        data = response.json()
        assert "name" in data
        assert "version" in data
        assert "docs" in data

    def test_health_endpoint(self, client):
        """Test health check endpoint."""
        response = client.get("/health")

        assert response.status_code == 200
        data = response.json()
        assert "status" in data
        assert data["status"] == "healthy"

    def test_docs_endpoint(self, client):
        """Test OpenAPI docs are accessible."""
        response = client.get("/docs")
        assert response.status_code == 200

    def test_openapi_schema(self, client):
        """Test OpenAPI schema endpoint."""
        response = client.get("/openapi.json")

        assert response.status_code == 200
        schema = response.json()
        assert "openapi" in schema
        assert "paths" in schema


# ============================================================================
# Test Create Entity
# ============================================================================


class TestCreateEntity:
    """Test POST /api/v1/github/entities"""

    def test_create_entity(self, client, sample_entity_data):
        """Test creating a valid entity."""
        response = client.post("/api/v1/github/entities", json=sample_entity_data)

        assert response.status_code == 201
        data = response.json()
        assert data["success"] is True
        assert data["entity"]["name"] == sample_entity_data["name"]
        assert "id" in data["entity"]

    def test_create_entity_minimal(self, client):
        """Test creating entity with only required fields."""
        response = client.post(
            "/api/v1/github/entities", json={"name": "Minimal Entity"}
        )

        assert response.status_code == 201
        data = response.json()
        assert data["entity"]["name"] == "Minimal Entity"

    def test_create_entity_invalid_name(self, client):
        """Test creating entity with invalid name."""
        response = client.post(
            "/api/v1/github/entities", json={"name": ""}  # Empty name
        )

        assert response.status_code == 400
        data = response.json()
        assert "error" in data

    def test_create_entity_missing_name(self, client):
        """Test creating entity without name."""
        response = client.post("/api/v1/github/entities", json={})

        assert response.status_code == 422  # Validation error


# ============================================================================
# Test Get Entity
# ============================================================================


class TestGetEntity:
    """Test GET /api/v1/github/entities/{entity_id}"""

    def test_get_existing_entity(self, client, sample_entity_data):
        """Test getting an existing entity."""
        # Create entity
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        # Get entity
        response = client.get(f"/api/v1/github/entities/{entity_id}")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == entity_id
        assert data["name"] == sample_entity_data["name"]

    def test_get_nonexistent_entity(self, client):
        """Test getting non-existent entity returns 404."""
        fake_id = str(uuid4())
        response = client.get(f"/api/v1/github/entities/{fake_id}")

        assert response.status_code == 404
        data = response.json()
        assert "error" in data
        assert data["error"] == "NOT_FOUND"

    def test_get_invalid_uuid(self, client):
        """Test get with invalid UUID format."""
        response = client.get("/api/v1/github/entities/not-a-uuid")

        assert response.status_code == 422  # Validation error


# ============================================================================
# Test List Entities
# ============================================================================


class TestListEntities:
    """Test GET /api/v1/github/entities"""

    def test_list_empty(self, client):
        """Test listing when no entities exist."""
        response = client.get("/api/v1/github/entities")

        assert response.status_code == 200
        data = response.json()
        assert data["entities"] == []
        assert data["total"] == 0

    def test_list_with_entities(self, client):
        """Test listing with existing entities."""
        # Create some entities
        for i in range(3):
            client.post("/api/v1/github/entities", json={"name": f"Entity {i}"})

        response = client.get("/api/v1/github/entities")

        assert response.status_code == 200
        data = response.json()
        assert len(data["entities"]) == 3
        assert data["total"] == 3

    def test_list_with_status_filter(self, client, sample_entity_data):
        """Test listing with status filter."""
        # Create entity and update its status
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        client.post(
            f"/api/v1/github/entities/{entity_id}/status", json={"status": "active"}
        )

        # List active entities
        response = client.get("/api/v1/github/entities", params={"status": "active"})

        assert response.status_code == 200
        data = response.json()
        assert all(e["status"] == "active" for e in data["entities"])

    def test_list_with_name_filter(self, client):
        """Test listing with name filter."""
        # Create entities
        client.post("/api/v1/github/entities", json={"name": "Alpha"})
        client.post("/api/v1/github/entities", json={"name": "Beta"})
        client.post("/api/v1/github/entities", json={"name": "Alphabet"})

        # Filter by name
        response = client.get(
            "/api/v1/github/entities", params={"name_contains": "alpha"}
        )

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 2

    def test_list_with_pagination(self, client):
        """Test pagination."""
        # Create 10 entities
        for i in range(10):
            client.post("/api/v1/github/entities", json={"name": f"Entity {i}"})

        # Get first page
        response = client.get(
            "/api/v1/github/entities", params={"offset": 0, "limit": 5}
        )

        assert response.status_code == 200
        data = response.json()
        assert len(data["entities"]) == 5
        assert data["total"] == 10

        # Get second page
        response = client.get(
            "/api/v1/github/entities", params={"offset": 5, "limit": 5}
        )

        assert response.status_code == 200
        data = response.json()
        assert len(data["entities"]) == 5


# ============================================================================
# Test Update Entity
# ============================================================================


class TestUpdateEntity:
    """Test PUT /api/v1/github/entities/{entity_id}"""

    def test_update_entity(self, client, sample_entity_data):
        """Test updating an entity."""
        # Create entity
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        # Update entity
        update_data = {
            "name": "Updated Name",
            "description": "Updated description",
            "metadata": {"updated": True},
        }
        response = client.put(f"/api/v1/github/entities/{entity_id}", json=update_data)

        assert response.status_code == 200
        data = response.json()
        assert data["entity"]["name"] == "Updated Name"
        assert data["entity"]["description"] == "Updated description"

    def test_update_nonexistent_entity(self, client):
        """Test updating non-existent entity returns 404."""
        fake_id = str(uuid4())
        response = client.put(
            f"/api/v1/github/entities/{fake_id}", json={"name": "Updated"}
        )

        assert response.status_code == 404


# ============================================================================
# Test Partial Update Entity
# ============================================================================


class TestPatchEntity:
    """Test PATCH /api/v1/github/entities/{entity_id}"""

    def test_patch_entity_name_only(self, client, sample_entity_data):
        """Test partially updating only the name."""
        # Create entity
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        # Patch only name
        response = client.patch(
            f"/api/v1/github/entities/{entity_id}", json={"name": "Patched Name"}
        )

        assert response.status_code == 200
        data = response.json()
        assert data["entity"]["name"] == "Patched Name"
        assert data["entity"]["description"] == sample_entity_data["description"]


# ============================================================================
# Test Delete Entity
# ============================================================================


class TestDeleteEntity:
    """Test DELETE /api/v1/github/entities/{entity_id}"""

    def test_delete_entity(self, client, sample_entity_data):
        """Test deleting an entity."""
        # Create entity
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        # Delete entity
        response = client.delete(f"/api/v1/github/entities/{entity_id}")

        assert response.status_code == 204

        # Verify deleted
        get_response = client.get(f"/api/v1/github/entities/{entity_id}")
        assert get_response.status_code == 404

    def test_delete_nonexistent_entity(self, client):
        """Test deleting non-existent entity returns 404."""
        fake_id = str(uuid4())
        response = client.delete(f"/api/v1/github/entities/{fake_id}")

        assert response.status_code == 404


# ============================================================================
# Test Update Status
# ============================================================================


class TestUpdateStatus:
    """Test POST /api/v1/github/entities/{entity_id}/status"""

    def test_update_status(self, client, sample_entity_data):
        """Test updating entity status."""
        # Create entity
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        # Update to active
        response = client.post(
            f"/api/v1/github/entities/{entity_id}/status", json={"status": "active"}
        )

        assert response.status_code == 200
        data = response.json()
        assert data["entity"]["status"] == "active"

    def test_update_status_invalid_transition(self, client, sample_entity_data):
        """Test invalid status transition."""
        # Create entity, move to completed
        create_response = client.post(
            "/api/v1/github/entities", json=sample_entity_data
        )
        entity_id = create_response.json()["entity"]["id"]

        client.post(
            f"/api/v1/github/entities/{entity_id}/status", json={"status": "active"}
        )
        client.post(
            f"/api/v1/github/entities/{entity_id}/status", json={"status": "completed"}
        )

        # Try to transition from completed (should fail)
        response = client.post(
            f"/api/v1/github/entities/{entity_id}/status", json={"status": "active"}
        )

        assert response.status_code == 400
        data = response.json()
        assert "error" in data


# ============================================================================
# Test Bulk Operations
# ============================================================================


class TestBulkOperations:
    """Test bulk operations."""

    def test_bulk_delete(self, client):
        """Test bulk delete operation."""
        # Create multiple entities
        entity_ids = []
        for i in range(3):
            response = client.post(
                "/api/v1/github/entities", json={"name": f"Entity {i}"}
            )
            entity_ids.append(response.json()["entity"]["id"])

        # Bulk delete
        response = client.post("/api/v1/github/entities/bulk/delete", json=entity_ids)

        assert response.status_code == 200
        data = response.json()
        assert data["deleted_count"] == 3
        assert data["failed_count"] == 0


# ============================================================================
# Test Error Handling
# ============================================================================


class TestErrorHandling:
    """Test error response formats."""

    def test_validation_error_format(self, client):
        """Test validation error has correct format."""
        response = client.post("/api/v1/github/entities", json={"name": ""})  # Invalid

        assert response.status_code == 400
        data = response.json()
        assert "error" in data
        assert "message" in data
        assert "details" in data

    def test_not_found_error_format(self, client):
        """Test not found error has correct format."""
        fake_id = str(uuid4())
        response = client.get(f"/api/v1/github/entities/{fake_id}")

        assert response.status_code == 404
        data = response.json()
        assert data["error"] == "NOT_FOUND"
        assert "message" in data


# ============================================================================
# Test CORS
# ============================================================================


class TestCORS:
    """Test CORS configuration."""

    def test_cors_headers_present(self, client):
        """Test CORS headers are present in responses."""
        response = client.get(
            "/api/v1/github/entities", headers={"Origin": "http://example.com"}
        )

        assert "access-control-allow-origin" in response.headers
