"""Tests for GitHub CLI Interface (SAP-043)

Tests verify CLI commands, argument parsing, output formatting,
and error handling.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

import json
from uuid import uuid4

import pytest
from click.testing import CliRunner
from github.interfaces.cli import cli


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def runner():
    """Create CLI test runner."""
    return CliRunner()


# ============================================================================
# Test Create Command
# ============================================================================


class TestCreateCommand:
    """Test create command."""

    def test_create_basic(self, runner):
        """Test creating entity with basic arguments."""
        result = runner.invoke(cli, ["create", "Test Entity"])

        assert result.exit_code == 0
        assert "Test Entity" in result.output

    def test_create_with_description(self, runner):
        """Test creating entity with description."""
        result = runner.invoke(
            cli, ["create", "Test Entity", "--description", "Test description"]
        )

        assert result.exit_code == 0
        assert "Test Entity" in result.output

    def test_create_with_metadata(self, runner):
        """Test creating entity with metadata."""
        result = runner.invoke(
            cli,
            [
                "create",
                "Test Entity",
                "--metadata",
                "key1=value1",
                "--metadata",
                "key2=value2",
            ],
        )

        assert result.exit_code == 0

    def test_create_json_output(self, runner):
        """Test create with JSON output format."""
        result = runner.invoke(cli, ["--format", "json", "create", "Test Entity"])

        assert result.exit_code == 0
        data = json.loads(result.output)
        assert "id" in data
        assert data["name"] == "Test Entity"

    def test_create_invalid_metadata_format(self, runner):
        """Test create with invalid metadata format."""
        result = runner.invoke(
            cli, ["create", "Test Entity", "--metadata", "invalid-format"]
        )

        assert result.exit_code == 1
        assert "Invalid metadata format" in result.output


# ============================================================================
# Test List Command
# ============================================================================


class TestListCommand:
    """Test list command."""

    def test_list_empty(self, runner):
        """Test listing when no entities exist."""
        result = runner.invoke(cli, ["list"])

        assert result.exit_code == 0
        assert "No entities found" in result.output or "0" in result.output

    def test_list_with_entities(self, runner):
        """Test listing with existing entities."""
        # Create some entities first
        for i in range(3):
            runner.invoke(cli, ["create", f"Entity {i}"])

        result = runner.invoke(cli, ["list"])

        assert result.exit_code == 0
        assert "Entity 0" in result.output or "Entity" in result.output

    def test_list_json_format(self, runner):
        """Test list with JSON output."""
        # Create entity
        runner.invoke(cli, ["create", "Test Entity"])

        result = runner.invoke(cli, ["--format", "json", "list"])

        assert result.exit_code == 0
        data = json.loads(result.output)
        assert "entities" in data
        assert "total" in data

    def test_list_with_status_filter(self, runner):
        """Test list with status filter."""
        result = runner.invoke(cli, ["list", "--status", "active"])

        assert result.exit_code == 0

    def test_list_with_name_filter(self, runner):
        """Test list with name filter."""
        result = runner.invoke(cli, ["list", "--name-contains", "test"])

        assert result.exit_code == 0

    def test_list_with_pagination(self, runner):
        """Test list with pagination."""
        result = runner.invoke(cli, ["list", "--offset", "0", "--limit", "10"])

        assert result.exit_code == 0


# ============================================================================
# Test Get Command
# ============================================================================


class TestGetCommand:
    """Test get command."""

    def test_get_existing_entity(self, runner):
        """Test getting an existing entity."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Test Entity"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Get entity
        result = runner.invoke(cli, ["get", entity_id])

        assert result.exit_code == 0
        assert "Test Entity" in result.output

    def test_get_nonexistent_entity(self, runner):
        """Test getting non-existent entity."""
        fake_id = str(uuid4())
        result = runner.invoke(cli, ["get", fake_id])

        assert result.exit_code == 1
        assert "not found" in result.output.lower()

    def test_get_invalid_uuid(self, runner):
        """Test get with invalid UUID format."""
        result = runner.invoke(cli, ["get", "not-a-uuid"])

        assert result.exit_code == 1
        assert "Invalid UUID" in result.output

    def test_get_json_format(self, runner):
        """Test get with JSON output."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Test Entity"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Get with JSON format
        result = runner.invoke(cli, ["--format", "json", "get", entity_id])

        assert result.exit_code == 0
        data = json.loads(result.output)
        assert data["id"] == entity_id


# ============================================================================
# Test Update Command
# ============================================================================


class TestUpdateCommand:
    """Test update command."""

    def test_update_name(self, runner):
        """Test updating entity name."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Original Name"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Update name
        result = runner.invoke(cli, ["update", entity_id, "--name", "Updated Name"])

        assert result.exit_code == 0
        assert "Updated Name" in result.output

    def test_update_description(self, runner):
        """Test updating entity description."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Test Entity"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Update description
        result = runner.invoke(
            cli, ["update", entity_id, "--description", "New description"]
        )

        assert result.exit_code == 0

    def test_update_no_fields_provided(self, runner):
        """Test update with no fields fails."""
        fake_id = str(uuid4())
        result = runner.invoke(cli, ["update", fake_id])

        assert result.exit_code == 1
        assert "at least one update field" in result.output.lower()


# ============================================================================
# Test Delete Command
# ============================================================================


class TestDeleteCommand:
    """Test delete command."""

    def test_delete_with_yes_flag(self, runner):
        """Test delete with --yes flag (no confirmation)."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Test Entity"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Delete with --yes
        result = runner.invoke(cli, ["delete", entity_id, "--yes"])

        assert result.exit_code == 0
        assert "deleted successfully" in result.output.lower()

    def test_delete_nonexistent_entity(self, runner):
        """Test deleting non-existent entity."""
        fake_id = str(uuid4())
        result = runner.invoke(cli, ["delete", fake_id, "--yes"])

        assert result.exit_code == 1
        assert "not found" in result.output.lower()


# ============================================================================
# Test Status Command
# ============================================================================


class TestStatusCommand:
    """Test status command."""

    def test_update_status(self, runner):
        """Test updating entity status."""
        # Create entity
        create_result = runner.invoke(
            cli, ["--format", "json", "create", "Test Entity"]
        )
        entity_data = json.loads(create_result.output)
        entity_id = entity_data["id"]

        # Update to active
        result = runner.invoke(cli, ["status", entity_id, "active"])

        assert result.exit_code == 0

    def test_update_status_invalid_value(self, runner):
        """Test update with invalid status value."""
        fake_id = str(uuid4())
        result = runner.invoke(cli, ["status", fake_id, "invalid-status"])

        # Should fail at argument parsing level
        assert result.exit_code != 0


# ============================================================================
# Test Health Command
# ============================================================================


class TestHealthCommand:
    """Test health command."""

    def test_health_check(self, runner):
        """Test health check command."""
        result = runner.invoke(cli, ["health"])

        assert result.exit_code == 0
        assert "healthy" in result.output.lower() or "status" in result.output.lower()

    def test_health_json_format(self, runner):
        """Test health check with JSON output."""
        result = runner.invoke(cli, ["--format", "json", "health"])

        assert result.exit_code == 0
        data = json.loads(result.output)
        assert "status" in data


# ============================================================================
# Test Output Formats
# ============================================================================


class TestOutputFormats:
    """Test different output formats."""

    def test_table_format(self, runner):
        """Test table output format (default)."""
        result = runner.invoke(cli, ["health"])
        assert result.exit_code == 0

    def test_json_format(self, runner):
        """Test JSON output format."""
        result = runner.invoke(cli, ["--format", "json", "health"])
        assert result.exit_code == 0
        json.loads(result.output)  # Should parse as JSON

    def test_yaml_format(self, runner):
        """Test YAML output format."""
        result = runner.invoke(cli, ["--format", "yaml", "health"])
        assert result.exit_code == 0
        assert ":" in result.output  # YAML uses colons
