"""Tests for GitHub Core Models (SAP-042)

Tests verify Pydantic model validation, serialization, and business logic
for domain models.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from datetime import datetime, timedelta
from uuid import UUID, uuid4

import pytest
from pydantic import ValidationError

from chora_github.core.models import (
    GithubEntity,
    GithubFilter,
    GithubListResponse,
    GithubRequest,
    GithubResponse,
    GithubStatus,
)


# ============================================================================
# Test GithubRequest
# ============================================================================


class TestGithubRequest:
    """Test cases for GithubRequest model."""

    def test_create_valid_request(self):
        """Test creating a valid request."""
        request = GithubRequest(
            name="Test Entity",
            description="Test description",
            metadata={"key": "value"},
        )

        assert request.name == "Test Entity"
        assert request.description == "Test description"
        assert request.metadata == {"key": "value"}

    def test_create_minimal_request(self):
        """Test creating request with only required fields."""
        request = GithubRequest(name="Minimal")

        assert request.name == "Minimal"
        assert request.description is None
        assert request.metadata == {}

    def test_name_validation_strips_whitespace(self):
        """Test that name is stripped of whitespace."""
        request = GithubRequest(name="  Padded  ")
        assert request.name == "Padded"

    def test_name_validation_empty_string(self):
        """Test that empty name raises validation error."""
        with pytest.raises(ValidationError) as exc_info:
            GithubRequest(name="")

        assert "Name cannot be empty" in str(exc_info.value)

    def test_name_validation_whitespace_only(self):
        """Test that whitespace-only name raises validation error."""
        with pytest.raises(ValidationError) as exc_info:
            GithubRequest(name="   ")

        assert "Name cannot be empty" in str(exc_info.value)

    def test_name_max_length(self):
        """Test name maximum length validation."""
        long_name = "x" * 201
        with pytest.raises(ValidationError) as exc_info:
            GithubRequest(name=long_name)

        assert "max_length" in str(exc_info.value).lower()

    def test_description_max_length(self):
        """Test description maximum length validation."""
        long_desc = "x" * 2001
        with pytest.raises(ValidationError) as exc_info:
            GithubRequest(name="Test", description=long_desc)

        assert "max_length" in str(exc_info.value).lower()

    def test_json_serialization(self):
        """Test model can be serialized to JSON."""
        request = GithubRequest(
            name="Test", description="Description", metadata={"key": "value"}
        )

        json_str = request.model_dump_json()
        assert "Test" in json_str
        assert "Description" in json_str


# ============================================================================
# Test GithubEntity
# ============================================================================


class TestGithubEntity:
    """Test cases for GithubEntity model."""

    def test_create_entity(self):
        """Test creating an entity with default values."""
        entity = GithubEntity(name="Test Entity")

        assert isinstance(entity.id, UUID)
        assert entity.name == "Test Entity"
        assert entity.status == GithubStatus.PENDING
        assert isinstance(entity.created_at, datetime)
        assert isinstance(entity.updated_at, datetime)

    def test_entity_with_all_fields(self):
        """Test creating entity with all fields specified."""
        entity_id = uuid4()
        created = datetime.utcnow()

        entity = GithubEntity(
            id=entity_id,
            name="Full Entity",
            description="Full description",
            status=GithubStatus.ACTIVE,
            metadata={"key": "value"},
            created_at=created,
            updated_at=created,
        )

        assert entity.id == entity_id
        assert entity.name == "Full Entity"
        assert entity.description == "Full description"
        assert entity.status == GithubStatus.ACTIVE
        assert entity.metadata == {"key": "value"}
        assert entity.created_at == created

    def test_to_dict_method(self):
        """Test entity to_dict conversion."""
        entity = GithubEntity(name="Test", description="Description")

        data = entity.to_dict()

        assert isinstance(data, dict)
        assert isinstance(data["id"], str)
        assert data["name"] == "Test"
        assert isinstance(data["created_at"], str)
        assert isinstance(data["updated_at"], str)

    def test_status_enum_values(self):
        """Test all status enum values."""
        for status in GithubStatus:
            entity = GithubEntity(name="Test", status=status)
            assert entity.status == status


# ============================================================================
# Test GithubResponse
# ============================================================================


class TestGithubResponse:
    """Test cases for GithubResponse model."""

    def test_create_response(self):
        """Test creating a response."""
        entity = GithubEntity(name="Test")
        response = GithubResponse(entity=entity, message="Success", success=True)

        assert response.entity == entity
        assert response.message == "Success"
        assert response.success is True

    def test_response_with_defaults(self):
        """Test response with default values."""
        entity = GithubEntity(name="Test")
        response = GithubResponse(entity=entity)

        assert response.entity == entity
        assert response.message is None
        assert response.success is True


# ============================================================================
# Test GithubListResponse
# ============================================================================


class TestGithubListResponse:
    """Test cases for GithubListResponse model."""

    def test_create_list_response(self):
        """Test creating a list response."""
        entities = [GithubEntity(name=f"Entity {i}") for i in range(5)]

        response = GithubListResponse(entities=entities, total=10, offset=0, limit=5)

        assert len(response.entities) == 5
        assert response.total == 10
        assert response.offset == 0
        assert response.limit == 5

    def test_empty_list_response(self):
        """Test empty list response with defaults."""
        response = GithubListResponse()

        assert response.entities == []
        assert response.total == 0
        assert response.offset == 0
        assert response.limit == 100

    def test_limit_validation(self):
        """Test limit bounds validation."""
        # Test minimum
        with pytest.raises(ValidationError):
            GithubListResponse(limit=0)

        # Test maximum
        with pytest.raises(ValidationError):
            GithubListResponse(limit=1001)


# ============================================================================
# Test GithubFilter
# ============================================================================


class TestGithubFilter:
    """Test cases for GithubFilter model."""

    def test_create_empty_filter(self):
        """Test creating filter with defaults."""
        filters = GithubFilter()

        assert filters.status is None
        assert filters.name_contains is None
        assert filters.created_after is None
        assert filters.created_before is None
        assert filters.offset == 0
        assert filters.limit == 100

    def test_create_filter_with_all_fields(self):
        """Test creating filter with all fields."""
        now = datetime.utcnow()
        yesterday = now - timedelta(days=1)

        filters = GithubFilter(
            status=GithubStatus.ACTIVE,
            name_contains="test",
            created_after=yesterday,
            created_before=now,
            offset=10,
            limit=50,
        )

        assert filters.status == GithubStatus.ACTIVE
        assert filters.name_contains == "test"
        assert filters.created_after == yesterday
        assert filters.created_before == now
        assert filters.offset == 10
        assert filters.limit == 50

    def test_offset_validation(self):
        """Test offset cannot be negative."""
        with pytest.raises(ValidationError):
            GithubFilter(offset=-1)

    def test_limit_bounds(self):
        """Test limit validation."""
        with pytest.raises(ValidationError):
            GithubFilter(limit=0)

        with pytest.raises(ValidationError):
            GithubFilter(limit=1001)


# ============================================================================
# Integration Tests
# ============================================================================


class TestModelsIntegration:
    """Integration tests for model interactions."""

    def test_request_to_entity_to_response(self):
        """Test typical flow: request → entity → response."""
        # Create request
        request = GithubRequest(
            name="Integration Test",
            description="Test description",
            metadata={"source": "test"},
        )

        # Create entity from request
        entity = GithubEntity(
            name=request.name,
            description=request.description,
            metadata=request.metadata,
        )

        # Create response
        response = GithubResponse(
            entity=entity, message="Created successfully", success=True
        )

        assert response.entity.name == request.name
        assert response.entity.description == request.description
        assert response.success is True

    def test_filter_with_list_response(self):
        """Test filter used with list response."""
        filters = GithubFilter(status=GithubStatus.ACTIVE, limit=10)

        # Simulate filtered results
        entities = [
            GithubEntity(name=f"Entity {i}", status=GithubStatus.ACTIVE)
            for i in range(5)
        ]

        response = GithubListResponse(
            entities=entities, total=5, offset=filters.offset, limit=filters.limit
        )

        assert len(response.entities) == 5
        assert all(e.status == GithubStatus.ACTIVE for e in response.entities)
