"""Tests for GitHub Core Exceptions (SAP-042)

Tests verify exception hierarchy, error messages, and serialization
for domain exceptions.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from chora_github.core.exceptions import (
    GithubConfigError,
    GithubConflictError,
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
    GithubRateLimitError,
    GithubServiceError,
    GithubTimeoutError,
    GithubValidationError,
    get_error_code,
    get_error_details,
    is_github_error,
)


# ============================================================================
# Test Base Exception
# ============================================================================


class TestGithubError:
    """Test base exception class."""

    def test_create_base_error(self):
        """Test creating base error with message."""
        error = GithubError("Test error")

        assert str(error) == "Test error"
        assert error.message == "Test error"
        assert error.code == "GithubError"
        assert error.details == {}

    def test_error_with_code(self):
        """Test error with custom code."""
        error = GithubError("Test error", code="CUSTOM_CODE")

        assert error.code == "CUSTOM_CODE"

    def test_error_with_details(self):
        """Test error with additional details."""
        error = GithubError("Test error", details={"key": "value", "count": 42})

        assert error.details == {"key": "value", "count": 42}

    def test_error_to_dict(self):
        """Test error serialization to dictionary."""
        error = GithubError("Test error", code="TEST_ERROR", details={"field": "name"})

        data = error.to_dict()

        assert data["error"] == "TEST_ERROR"
        assert data["message"] == "Test error"
        assert data["details"] == {"field": "name"}

    def test_error_str_with_details(self):
        """Test string representation includes details."""
        error = GithubError("Test error", details={"key": "value"})

        error_str = str(error)
        assert "Test error" in error_str
        assert "details" in error_str


# ============================================================================
# Test Validation Error
# ============================================================================


class TestGithubValidationError:
    """Test validation error class."""

    def test_create_validation_error(self):
        """Test creating validation error."""
        error = GithubValidationError("Invalid input")

        assert isinstance(error, GithubError)
        assert error.message == "Invalid input"
        assert error.code == "VALIDATION_ERROR"

    def test_validation_error_with_field(self):
        """Test validation error with field name."""
        error = GithubValidationError("Invalid value", field="email")

        assert error.details["field"] == "email"

    def test_validation_error_with_value(self):
        """Test validation error with invalid value."""
        error = GithubValidationError("Invalid value", field="age", value=-1)

        assert error.details["field"] == "age"
        assert error.details["value"] == -1

    def test_validation_error_with_all_params(self):
        """Test validation error with all parameters."""
        error = GithubValidationError(
            "Invalid email format",
            field="email",
            value="not-an-email",
            details={"expected_format": "user@domain.com"},
        )

        assert error.details["field"] == "email"
        assert error.details["value"] == "not-an-email"
        assert error.details["expected_format"] == "user@domain.com"


# ============================================================================
# Test Not Found Error
# ============================================================================


class TestGithubNotFoundError:
    """Test not found error class."""

    def test_create_not_found_error(self):
        """Test creating not found error."""
        error = GithubNotFoundError("Entity not found")

        assert isinstance(error, GithubError)
        assert error.code == "NOT_FOUND"

    def test_not_found_with_entity_id(self):
        """Test not found error with entity ID."""
        error = GithubNotFoundError(
            "Entity not found", entity_id="123e4567-e89b-12d3-a456-426614174000"
        )

        assert "123e4567-e89b-12d3-a456-426614174000" in error.details["entity_id"]

    def test_not_found_with_entity_type(self):
        """Test not found error with entity type."""
        error = GithubNotFoundError("Entity not found", entity_type="User")

        assert error.details["entity_type"] == "User"


# ============================================================================
# Test Conflict Error
# ============================================================================


class TestGithubConflictError:
    """Test conflict error class."""

    def test_create_conflict_error(self):
        """Test creating conflict error."""
        error = GithubConflictError("Duplicate entry")

        assert isinstance(error, GithubError)
        assert error.code == "CONFLICT"

    def test_conflict_with_conflicting_id(self):
        """Test conflict error with conflicting entity ID."""
        error = GithubConflictError("Duplicate entry", conflicting_id="existing-123")

        assert error.details["conflicting_id"] == "existing-123"


# ============================================================================
# Test Permission Error
# ============================================================================


class TestGithubPermissionError:
    """Test permission error class."""

    def test_create_permission_error(self):
        """Test creating permission error."""
        error = GithubPermissionError("Access denied")

        assert isinstance(error, GithubError)
        assert error.code == "PERMISSION_DENIED"

    def test_permission_with_required_permission(self):
        """Test permission error with required permission."""
        error = GithubPermissionError("Access denied", required_permission="admin")

        assert error.details["required_permission"] == "admin"


# ============================================================================
# Test Service Error
# ============================================================================


class TestGithubServiceError:
    """Test service error class."""

    def test_create_service_error(self):
        """Test creating service error."""
        error = GithubServiceError("Service unavailable")

        assert isinstance(error, GithubError)
        assert error.code == "SERVICE_ERROR"

    def test_service_error_with_operation(self):
        """Test service error with operation name."""
        error = GithubServiceError("Operation failed", operation="database_query")

        assert error.details["operation"] == "database_query"

    def test_service_error_with_cause(self):
        """Test service error with underlying cause."""
        cause = ValueError("Invalid connection string")
        error = GithubServiceError("Database connection failed", cause=cause)

        assert "Invalid connection string" in error.details["cause"]
        assert error.details["cause_type"] == "ValueError"


# ============================================================================
# Test Rate Limit Error
# ============================================================================


class TestGithubRateLimitError:
    """Test rate limit error class."""

    def test_create_rate_limit_error(self):
        """Test creating rate limit error."""
        error = GithubRateLimitError("Rate limit exceeded")

        assert isinstance(error, GithubError)
        assert error.code == "RATE_LIMIT_EXCEEDED"

    def test_rate_limit_with_all_params(self):
        """Test rate limit error with all parameters."""
        error = GithubRateLimitError(
            "Rate limit exceeded", limit=100, window_seconds=60, retry_after_seconds=30
        )

        assert error.details["limit"] == 100
        assert error.details["window_seconds"] == 60
        assert error.details["retry_after_seconds"] == 30


# ============================================================================
# Test Timeout Error
# ============================================================================


class TestGithubTimeoutError:
    """Test timeout error class."""

    def test_create_timeout_error(self):
        """Test creating timeout error."""
        error = GithubTimeoutError("Operation timed out")

        assert isinstance(error, GithubError)
        assert error.code == "TIMEOUT"

    def test_timeout_with_duration(self):
        """Test timeout error with duration."""
        error = GithubTimeoutError(
            "Query timed out", timeout_seconds=30.0, operation="database_query"
        )

        assert error.details["timeout_seconds"] == 30.0
        assert error.details["operation"] == "database_query"


# ============================================================================
# Test Config Error
# ============================================================================


class TestGithubConfigError:
    """Test configuration error class."""

    def test_create_config_error(self):
        """Test creating config error."""
        error = GithubConfigError("Missing configuration")

        assert isinstance(error, GithubError)
        assert error.code == "CONFIG_ERROR"

    def test_config_error_with_key(self):
        """Test config error with config key."""
        error = GithubConfigError("Missing required config", config_key="DATABASE_URL")

        assert error.details["config_key"] == "DATABASE_URL"


# ============================================================================
# Test Helper Functions
# ============================================================================


class TestHelperFunctions:
    """Test helper utility functions."""

    def test_is_github_error_true(self):
        """Test is_error returns True for domain errors."""
        error = GithubValidationError("Test")
        assert is_github_error(error) is True

    def test_is_github_error_false(self):
        """Test is_error returns False for non-domain errors."""
        error = ValueError("Test")
        assert is_github_error(error) is False

    def test_get_error_code_for_domain_error(self):
        """Test get_error_code for domain error."""
        error = GithubNotFoundError("Not found")
        code = get_error_code(error)

        assert code == "NOT_FOUND"

    def test_get_error_code_for_generic_error(self):
        """Test get_error_code for generic error."""
        error = RuntimeError("Test")
        code = get_error_code(error)

        assert code == "UNKNOWN_ERROR"

    def test_get_error_details_for_domain_error(self):
        """Test get_error_details for domain error."""
        error = GithubValidationError("Invalid", field="name", value="x")
        details = get_error_details(error)

        assert details["error"] == "VALIDATION_ERROR"
        assert details["message"] == "Invalid"
        assert details["details"]["field"] == "name"

    def test_get_error_details_for_generic_error(self):
        """Test get_error_details for generic error."""
        error = ValueError("Test error")
        details = get_error_details(error)

        assert details["error"] == "ValueError"
        assert details["message"] == "Test error"
        assert details["details"] == {}


# ============================================================================
# Test Exception Hierarchy
# ============================================================================


class TestExceptionHierarchy:
    """Test exception inheritance hierarchy."""

    def test_all_errors_inherit_from_base(self):
        """Test all domain errors inherit from base error."""
        exceptions = [
            GithubValidationError("test"),
            GithubNotFoundError("test"),
            GithubConflictError("test"),
            GithubPermissionError("test"),
            GithubServiceError("test"),
            GithubRateLimitError("test"),
            GithubTimeoutError("test"),
            GithubConfigError("test"),
        ]

        for exc in exceptions:
            assert isinstance(exc, GithubError)
            assert isinstance(exc, Exception)

    def test_catch_all_domain_errors(self):
        """Test catching all domain errors with base class."""
        try:
            raise GithubValidationError("Test")
        except GithubError as e:
            assert e.message == "Test"

        try:
            raise GithubNotFoundError("Test")
        except GithubError as e:
            assert e.message == "Test"
