"""GitHub - MCP Interface (SAP-043)

Model Context Protocol interface using FastMCP. Provides tools and
resources for AI assistants like Claude to interact with GitHub repositories.

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (8 tools)
"""

from fastmcp import FastMCP

from .tools import register_tools
from .resources import register_resources

# Export for testing
__all__ = ["mcp", "create_mcp_server"]


# ============================================================================
# MCP Server Setup
# ============================================================================


def create_mcp_server() -> FastMCP:
    """Create and configure MCP server for GitHub operations.

    Returns:
        Configured FastMCP server instance with GitHub tools and resources
    """
    mcp = FastMCP(
        name="mcp-server-github",
        version="1.0.0",
        description="GitHub integration server with multi-interface support (CLI, REST, MCP). "
                    "Provides 8 tools for managing issues, pull requests, and repository files."
    )

    # Register tools and resources
    register_tools(mcp)
    # TODO: Resources disabled - FastMCP doesn't support URI templates
    # Need to revisit resource implementation pattern
    # register_resources(mcp)

    return mcp


# ============================================================================
# Server Instance
# ============================================================================


# Only create server instance if not in test mode
# Tests should import tools directly and mock services
import os
mcp = None if os.getenv("PYTEST_CURRENT_TEST") else create_mcp_server()


# ============================================================================
# Entry Point
# ============================================================================


def main():
    """Main entry point for GitHub MCP server."""
    if mcp is None:
        # Create server if not already created (e.g., in tests)
        server = create_mcp_server()
        server.run()
    else:
        mcp.run()


if __name__ == "__main__":
    main()
