"""GitHub - MCP Resources (SAP-043)

MCP resource definitions for GitHub. Resources provide read-only context
that AI assistants can reference without making explicit tool calls.

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (3 resources)
"""

import json
import os
from typing import Optional

from fastmcp import FastMCP

from chora_github.core.services import GithubToolService
from chora_github.core.models import (
    ListIssuesRequest,
    ListPRsRequest,
    ListRepoFilesRequest,
)
from chora_github.core.exceptions import GithubError


# ============================================================================
# Namespace Configuration
# ============================================================================


NAMESPACE = "github"


def make_resource_uri(resource_type: str, *parts: str) -> str:
    """Create namespaced resource URI.

    Args:
        resource_type: Resource type (repo, issue, pr, etc.)
        *parts: URI path parts

    Returns:
        Namespaced resource URI (e.g., "github://repo/octocat/Hello-World/issues")
    """
    path = "/".join(parts)
    return f"{NAMESPACE}://{resource_type}/{path}"


# ============================================================================
# Helper Functions
# ============================================================================


def _get_service(token: Optional[str] = None) -> GithubToolService:
    """Get GitHub service instance with token.

    Args:
        token: GitHub PAT (optional, uses GITHUB_TOKEN env if not provided)

    Returns:
        GithubToolService instance

    Raises:
        ValueError: If no token provided and GITHUB_TOKEN env not set
    """
    github_token = token or os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError(
            "GitHub token required. Set GITHUB_TOKEN environment variable."
        )
    return GithubToolService(token=github_token)


# ============================================================================
# Resource Registration
# ============================================================================


def register_resources(mcp: FastMCP) -> None:
    """Register all GitHub resources with MCP server.

    Resources provide read-only context about repositories, issues, PRs, etc.
    AI assistants can reference these URIs to get current state information.

    Args:
        mcp: FastMCP server instance
    """

    # ========================================================================
    # Resource 1: Repository Issues
    # ========================================================================

    @mcp.resource(uri_template=make_resource_uri("repo", "{owner}", "{repo}", "issues"))
    async def get_repo_issues(owner: str, repo: str) -> str:
        """Get all open issues in a repository as a resource.

        This resource provides a list of all open issues, useful for AI assistants
        to understand current work items without explicit tool calls.

        URI Pattern: github://repo/{owner}/{repo}/issues

        Args:
            owner: Repository owner
            repo: Repository name

        Returns:
            JSON string with list of open issues

        Example URI:
            github://repo/octocat/Hello-World/issues
        """
        try:
            service = _get_service()
            request = ListIssuesRequest(owner=owner, repo=repo, state="open")
            response = service.list_issues(request)

            # Format as resource
            resource_data = {
                "uri": make_resource_uri("repo", owner, repo, "issues"),
                "name": f"{owner}/{repo} Issues",
                "description": f"Open issues in {owner}/{repo}",
                "mime_type": "application/json",
                "data": response.model_dump(),
            }

            return json.dumps(resource_data, indent=2)

        except (GithubError, ValueError) as e:
            error_data = {
                "uri": make_resource_uri("repo", owner, repo, "issues"),
                "error": str(e),
            }
            return json.dumps(error_data, indent=2)

    # ========================================================================
    # Resource 2: Repository Pull Requests
    # ========================================================================

    @mcp.resource(uri_template=make_resource_uri("repo", "{owner}", "{repo}", "prs"))
    async def get_repo_prs(owner: str, repo: str) -> str:
        """Get all open pull requests in a repository as a resource.

        This resource provides a list of all open PRs, useful for AI assistants
        to understand current code review work without explicit tool calls.

        URI Pattern: github://repo/{owner}/{repo}/prs

        Args:
            owner: Repository owner
            repo: Repository name

        Returns:
            JSON string with list of open pull requests

        Example URI:
            github://repo/octocat/Hello-World/prs
        """
        try:
            service = _get_service()
            request = ListPRsRequest(owner=owner, repo=repo, state="open")
            response = service.list_prs(request)

            # Format as resource
            resource_data = {
                "uri": make_resource_uri("repo", owner, repo, "prs"),
                "name": f"{owner}/{repo} Pull Requests",
                "description": f"Open pull requests in {owner}/{repo}",
                "mime_type": "application/json",
                "data": response.model_dump(),
            }

            return json.dumps(resource_data, indent=2)

        except (GithubError, ValueError) as e:
            error_data = {
                "uri": make_resource_uri("repo", owner, repo, "prs"),
                "error": str(e),
            }
            return json.dumps(error_data, indent=2)

    # ========================================================================
    # Resource 3: Repository Files
    # ========================================================================

    @mcp.resource(uri_template=make_resource_uri("repo", "{owner}", "{repo}", "files"))
    async def get_repo_files(owner: str, repo: str) -> str:
        """Get root directory listing of a repository as a resource.

        This resource provides the top-level file structure, useful for AI assistants
        to understand repository organization without explicit tool calls.

        URI Pattern: github://repo/{owner}/{repo}/files

        Args:
            owner: Repository owner
            repo: Repository name

        Returns:
            JSON string with root directory listing

        Example URI:
            github://repo/octocat/Hello-World/files
        """
        try:
            service = _get_service()
            request = ListRepoFilesRequest(owner=owner, repo=repo, path="")
            response = service.list_repo_files(request)

            # Format as resource
            resource_data = {
                "uri": make_resource_uri("repo", owner, repo, "files"),
                "name": f"{owner}/{repo} Files",
                "description": f"Root directory listing for {owner}/{repo}",
                "mime_type": "application/json",
                "data": response.model_dump(),
            }

            return json.dumps(resource_data, indent=2)

        except (GithubError, ValueError) as e:
            error_data = {
                "uri": make_resource_uri("repo", owner, repo, "files"),
                "error": str(e),
            }
            return json.dumps(error_data, indent=2)


# ============================================================================
# Resource URI Examples
# ============================================================================


RESOURCE_EXAMPLES = [
    {
        "uri": "github://repo/octocat/Hello-World/issues",
        "description": "Open issues in octocat/Hello-World repository",
    },
    {
        "uri": "github://repo/octocat/Hello-World/prs",
        "description": "Open pull requests in octocat/Hello-World repository",
    },
    {
        "uri": "github://repo/octocat/Hello-World/files",
        "description": "Root directory listing for octocat/Hello-World repository",
    },
]
