"""GitHub - MCP Tools (SAP-043)

MCP tool definitions for GitHub operations. Tools are functions that
AI assistants can call to interact with GitHub repositories, issues, PRs, and files.

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (8 tools)
"""

import json
import os
from typing import Optional

from fastmcp import FastMCP

from chora_github.core.services import GithubToolService
from chora_github.core.models import (
    ListIssuesRequest,
    CreateIssueRequest,
    GetIssueRequest,
    UpdateIssueRequest,
    ListPRsRequest,
    GetPRRequest,
    GetFileContentsRequest,
    ListRepoFilesRequest,
)
from chora_github.core.exceptions import (
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
)


# ============================================================================
# Namespace Configuration
# ============================================================================


NAMESPACE = "github"


def make_tool_name(tool: str) -> str:
    """Create namespaced tool name.

    Args:
        tool: Tool name

    Returns:
        Namespaced tool name (e.g., "github:list_issues")
    """
    return f"{NAMESPACE}:{tool}"


# ============================================================================
# Helper Functions
# ============================================================================


def _get_service(token: Optional[str] = None) -> GithubToolService:
    """Get GitHub service instance with token.

    Args:
        token: GitHub PAT (optional, uses GITHUB_TOKEN env if not provided)

    Returns:
        GithubToolService instance

    Raises:
        ValueError: If no token provided and GITHUB_TOKEN env not set
    """
    github_token = token or os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError(
            "GitHub token required. Provide 'token' parameter or set GITHUB_TOKEN environment variable."
        )
    return GithubToolService(token=github_token)


def _format_success(data: dict) -> str:
    """Format successful response as JSON.

    Args:
        data: Response data dictionary

    Returns:
        JSON-formatted string
    """
    return json.dumps(data, indent=2)


def _format_error(error: Exception) -> str:
    """Format error response as JSON.

    Args:
        error: Exception that occurred

    Returns:
        JSON-formatted error string
    """
    error_data = {
        "success": False,
        "error": {
            "type": type(error).__name__,
            "message": str(error),
        },
    }
    return json.dumps(error_data, indent=2)


# ============================================================================
# Tool Registration
# ============================================================================


def register_tools(mcp: FastMCP) -> None:
    """Register all GitHub tools with MCP server.

    Args:
        mcp: FastMCP server instance
    """

    # ========================================================================
    # Tool 1: List Issues
    # ========================================================================

    @mcp.tool(name=make_tool_name("list_issues"))
    async def list_issues(
        owner: str,
        repo: str,
        state: str = "open",
        token: Optional[str] = None,
    ) -> str:
        """List issues in a GitHub repository.

        Use this tool to retrieve a list of issues from a repository. You can filter
        by state (open, closed, or all).

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            state: Issue state filter - "open", "closed", or "all" (default: "open")
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with list of issues, each containing:
            - number: Issue number
            - title: Issue title
            - state: open/closed
            - url: Issue URL
            - created_at: Creation timestamp
            - updated_at: Last update timestamp
            - body: Issue description
            - labels: List of label names
            - assignees: List of assigned usernames
            - author: Issue author username

        Example:
            >>> await list_issues("octocat", "Hello-World", "open")
            {
              "issues": [
                {
                  "number": 1,
                  "title": "Bug in feature X",
                  "state": "open",
                  "url": "https://github.com/octocat/Hello-World/issues/1",
                  ...
                }
              ],
              "count": 1
            }
        """
        try:
            service = _get_service(token)
            request = ListIssuesRequest(owner=owner, repo=repo, state=state)
            response = service.list_issues(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 2: Create Issue
    # ========================================================================

    @mcp.tool(name=make_tool_name("create_issue"))
    async def create_issue(
        owner: str,
        repo: str,
        title: str,
        body: Optional[str] = None,
        labels: Optional[list[str]] = None,
        assignees: Optional[list[str]] = None,
        token: Optional[str] = None,
    ) -> str:
        """Create a new issue in a GitHub repository.

        Use this tool to create a new issue. You can optionally set labels and assignees.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            title: Issue title (required)
            body: Issue description/body (optional)
            labels: List of label names to apply (optional)
            assignees: List of usernames to assign (optional)
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with created issue details including:
            - number: Newly created issue number
            - title: Issue title
            - state: Issue state (will be "open")
            - url: Issue URL
            - created_at: Creation timestamp
            - body: Issue description
            - labels: Applied labels
            - assignees: Assigned users

        Example:
            >>> await create_issue(
            ...     "octocat",
            ...     "Hello-World",
            ...     "Found a bug",
            ...     "The feature doesn't work as expected",
            ...     ["bug"],
            ...     ["octocat"]
            ... )
            {
              "issue": {
                "number": 42,
                "title": "Found a bug",
                "state": "open",
                ...
              }
            }
        """
        try:
            service = _get_service(token)
            request = CreateIssueRequest(
                owner=owner,
                repo=repo,
                title=title,
                body=body or "",
                labels=labels or [],
                assignees=assignees or [],
            )
            response = service.create_issue(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 3: Get Issue
    # ========================================================================

    @mcp.tool(name=make_tool_name("get_issue"))
    async def get_issue(
        owner: str,
        repo: str,
        issue_number: int,
        token: Optional[str] = None,
    ) -> str:
        """Get detailed information about a specific GitHub issue.

        Use this tool to retrieve full details of an issue by its number.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            issue_number: Issue number to retrieve
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with detailed issue information including:
            - number: Issue number
            - title: Issue title
            - state: open/closed
            - url: Issue URL
            - created_at: Creation timestamp
            - updated_at: Last update timestamp
            - body: Full issue description
            - labels: List of labels
            - assignees: List of assigned users
            - author: Issue author
            - comments_count: Number of comments

        Example:
            >>> await get_issue("octocat", "Hello-World", 1)
            {
              "issue": {
                "number": 1,
                "title": "Bug in feature X",
                "state": "open",
                "body": "Full description...",
                ...
              }
            }
        """
        try:
            service = _get_service(token)
            request = GetIssueRequest(owner=owner, repo=repo, issue_number=issue_number)
            response = service.get_issue(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 4: Update Issue
    # ========================================================================

    @mcp.tool(name=make_tool_name("update_issue"))
    async def update_issue(
        owner: str,
        repo: str,
        issue_number: int,
        title: Optional[str] = None,
        body: Optional[str] = None,
        state: Optional[str] = None,
        labels: Optional[list[str]] = None,
        assignees: Optional[list[str]] = None,
        token: Optional[str] = None,
    ) -> str:
        """Update an existing GitHub issue.

        Use this tool to modify an issue's title, body, state, labels, or assignees.
        Only provide the fields you want to update.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            issue_number: Issue number to update
            title: New issue title (optional, leave None to keep current)
            body: New issue body (optional, leave None to keep current)
            state: New issue state - "open" or "closed" (optional, leave None to keep current)
            labels: New list of labels (optional, leave None to keep current, empty list to clear)
            assignees: New list of assignees (optional, leave None to keep current, empty list to clear)
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with updated issue details

        Example:
            >>> await update_issue(
            ...     "octocat",
            ...     "Hello-World",
            ...     1,
            ...     state="closed",
            ...     labels=["bug", "fixed"]
            ... )
            {
              "issue": {
                "number": 1,
                "state": "closed",
                "labels": ["bug", "fixed"],
                ...
              }
            }
        """
        try:
            service = _get_service(token)
            request = UpdateIssueRequest(
                owner=owner,
                repo=repo,
                issue_number=issue_number,
                title=title,
                body=body,
                state=state,
                labels=labels,
                assignees=assignees,
            )
            response = service.update_issue(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 5: List Pull Requests
    # ========================================================================

    @mcp.tool(name=make_tool_name("list_prs"))
    async def list_prs(
        owner: str,
        repo: str,
        state: str = "open",
        token: Optional[str] = None,
    ) -> str:
        """List pull requests in a GitHub repository.

        Use this tool to retrieve a list of pull requests from a repository. You can filter
        by state (open, closed, or all).

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            state: PR state filter - "open", "closed", or "all" (default: "open")
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with list of pull requests, each containing:
            - number: PR number
            - title: PR title
            - state: open/closed/merged
            - url: PR URL
            - created_at: Creation timestamp
            - updated_at: Last update timestamp
            - body: PR description
            - head: Head branch
            - base: Base branch
            - author: PR author username
            - mergeable: Whether PR can be merged

        Example:
            >>> await list_prs("octocat", "Hello-World", "open")
            {
              "pull_requests": [
                {
                  "number": 5,
                  "title": "Add new feature",
                  "state": "open",
                  ...
                }
              ],
              "count": 1
            }
        """
        try:
            service = _get_service(token)
            request = ListPRsRequest(owner=owner, repo=repo, state=state)
            response = service.list_prs(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 6: Get Pull Request
    # ========================================================================

    @mcp.tool(name=make_tool_name("get_pr"))
    async def get_pr(
        owner: str,
        repo: str,
        pr_number: int,
        token: Optional[str] = None,
    ) -> str:
        """Get detailed information about a specific GitHub pull request.

        Use this tool to retrieve full details of a pull request by its number.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            pr_number: Pull request number to retrieve
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with detailed PR information including:
            - number: PR number
            - title: PR title
            - state: open/closed/merged
            - url: PR URL
            - created_at: Creation timestamp
            - updated_at: Last update timestamp
            - merged_at: Merge timestamp (if merged)
            - body: Full PR description
            - head: Head branch
            - base: Base branch
            - author: PR author
            - mergeable: Whether PR can be merged
            - changed_files: Number of changed files
            - additions: Lines added
            - deletions: Lines deleted

        Example:
            >>> await get_pr("octocat", "Hello-World", 5)
            {
              "pull_request": {
                "number": 5,
                "title": "Add new feature",
                "state": "open",
                "mergeable": true,
                ...
              }
            }
        """
        try:
            service = _get_service(token)
            request = GetPRRequest(owner=owner, repo=repo, pr_number=pr_number)
            response = service.get_pr(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 7: Get File Contents
    # ========================================================================

    @mcp.tool(name=make_tool_name("get_file_contents"))
    async def get_file_contents(
        owner: str,
        repo: str,
        path: str,
        ref: Optional[str] = None,
        token: Optional[str] = None,
    ) -> str:
        """Read the contents of a file from a GitHub repository.

        Use this tool to read file contents. Works for text files and returns
        base64-encoded content for binary files.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            path: File path within the repository (e.g., "src/main.py")
            ref: Git reference (branch, tag, or commit SHA). Defaults to repo's default branch
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with file information including:
            - path: File path
            - name: File name
            - content: File contents (decoded for text files)
            - sha: Git blob SHA
            - size: File size in bytes
            - type: "file"
            - encoding: Content encoding ("utf-8" for text, "base64" for binary)

        Example:
            >>> await get_file_contents("octocat", "Hello-World", "README.md")
            {
              "file": {
                "path": "README.md",
                "name": "README.md",
                "content": "# Hello World\\n\\nThis is a sample repository...",
                "size": 245,
                ...
              }
            }
        """
        try:
            service = _get_service(token)
            request = GetFileContentsRequest(owner=owner, repo=repo, path=path, ref=ref)
            response = service.get_file_contents(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)

    # ========================================================================
    # Tool 8: List Repository Files
    # ========================================================================

    @mcp.tool(name=make_tool_name("list_repo_files"))
    async def list_repo_files(
        owner: str,
        repo: str,
        path: str = "",
        ref: Optional[str] = None,
        token: Optional[str] = None,
    ) -> str:
        """List files and directories in a GitHub repository path.

        Use this tool to explore repository structure and list files in a directory.

        Args:
            owner: Repository owner (user or organization)
            repo: Repository name
            path: Directory path within repository (empty string for root, default: "")
            ref: Git reference (branch, tag, or commit SHA). Defaults to repo's default branch
            token: GitHub Personal Access Token (optional, uses GITHUB_TOKEN env if not provided)

        Returns:
            JSON string with list of files/directories, each containing:
            - name: File or directory name
            - path: Full path
            - type: "file" or "dir"
            - size: Size in bytes (0 for directories)
            - sha: Git blob/tree SHA

        Example:
            >>> await list_repo_files("octocat", "Hello-World", "src")
            {
              "files": [
                {
                  "name": "main.py",
                  "path": "src/main.py",
                  "type": "file",
                  "size": 1024,
                  ...
                },
                {
                  "name": "utils",
                  "path": "src/utils",
                  "type": "dir",
                  "size": 0,
                  ...
                }
              ],
              "count": 2
            }
        """
        try:
            service = _get_service(token)
            request = ListRepoFilesRequest(owner=owner, repo=repo, path=path, ref=ref)
            response = service.list_repo_files(request)
            return _format_success(response.model_dump())
        except (GithubError, GithubNotFoundError, GithubPermissionError, ValueError) as e:
            return _format_error(e)


# ============================================================================
# Tool Examples
# ============================================================================


TOOL_EXAMPLES = [
    {
        "tool": "github:list_issues",
        "description": "List issues in a repository",
    },
    {
        "tool": "github:create_issue",
        "description": "Create a new issue",
    },
    {
        "tool": "github:get_issue",
        "description": "Get issue details",
    },
    {
        "tool": "github:update_issue",
        "description": "Update an existing issue",
    },
    {
        "tool": "github:list_prs",
        "description": "List pull requests in a repository",
    },
    {
        "tool": "github:get_pr",
        "description": "Get pull request details",
    },
    {
        "tool": "github:get_file_contents",
        "description": "Get file contents from a repository",
    },
    {
        "tool": "github:list_repo_files",
        "description": "List files in a repository directory",
    },
]
