"""GitHub - CLI Interface (SAP-043)

Command-line interface using Click framework. Translates CLI commands
to core service calls and formats output for terminal display.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

import asyncio
from typing import Optional

import click
from github.core import create_github_service

from .commands import cli as cli_app
from .formatters import OutputFormat


# ============================================================================
# CLI Application Setup
# ============================================================================


@click.group()
@click.version_option(version="{{ version }}", prog_name="github")
@click.option(
    "--format",
    type=click.Choice(["json", "table", "yaml"], case_sensitive=False),
    default="table",
    help="Output format for results",
)
@click.pass_context
def cli(ctx: click.Context, format: str):
    """GitHub - CLI + REST only, no optional features

    A production-ready capability server with multi-interface support.
    """
    # Store format in context for commands to access
    ctx.ensure_object(dict)
    ctx.obj["format"] = OutputFormat(format.lower())

    # Create service instance (shared across commands in this invocation)
    ctx.obj["service"] = create_github_service()


# Import and register command groups
from .commands import (
    create_command,
    delete_command,
    get_command,
    health_command,
    list_command,
    status_command,
    update_command,
)


cli.add_command(create_command)
cli.add_command(get_command)
cli.add_command(list_command)
cli.add_command(update_command)
cli.add_command(delete_command)
cli.add_command(status_command)
cli.add_command(health_command)


# ============================================================================
# Entry Point
# ============================================================================


def main():
    """Main entry point for CLI."""
    cli()


if __name__ == "__main__":
    main()
