"""GitHub - Core Package (SAP-042)

This package contains interface-agnostic business logic that implements
the core capabilities. Following the core/interface separation pattern,
this code is shared across all interfaces (CLI, REST, MCP).

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from .exceptions import (
    GithubConfigError,
    GithubConflictError,
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
    GithubRateLimitError,
    GithubServiceError,
    GithubTimeoutError,
    GithubValidationError,
)
from .models import (  # Enums; Common data models; Request models (8 tools); Response models (8 tools); Tool metadata; Tool call envelope
    CreateIssueRequest,
    CreateIssueResponse,
    FileData,
    FileType,
    GetFileContentsRequest,
    GetFileContentsResponse,
    GetIssueRequest,
    GetIssueResponse,
    GetPRRequest,
    GetPRResponse,
    IssueData,
    IssueState,
    ListIssuesRequest,
    ListIssuesResponse,
    ListPRsRequest,
    ListPRsResponse,
    ListRepoFilesRequest,
    ListRepoFilesResponse,
    PRData,
    PRState,
    ToolCallRequest,
    ToolCallResponse,
    ToolDefinition,
    ToolParameter,
    UpdateIssueRequest,
    UpdateIssueResponse,
)


# Services not yet implemented - will be added in Phase 2.2.4
# from .services import (
#     GithubService,
#     GithubServiceBase,
#     create_github_service,
# )

__all__ = [
    "CreateIssueRequest",
    "CreateIssueResponse",
    "FileData",
    "FileType",
    "GetFileContentsRequest",
    "GetFileContentsResponse",
    "GetIssueRequest",
    "GetIssueResponse",
    "GetPRRequest",
    "GetPRResponse",
    "GithubConfigError",
    "GithubConflictError",
    # Services (not yet implemented - Phase 2.2.4)
    # "GithubService",
    # "GithubServiceBase",
    # "create_github_service",
    # Exceptions
    "GithubError",
    "GithubNotFoundError",
    "GithubPermissionError",
    "GithubRateLimitError",
    "GithubServiceError",
    "GithubTimeoutError",
    "GithubValidationError",
    # Common data models
    "IssueData",
    # Enums
    "IssueState",
    # Request models (8 tools)
    "ListIssuesRequest",
    # Response models (8 tools)
    "ListIssuesResponse",
    "ListPRsRequest",
    "ListPRsResponse",
    "ListRepoFilesRequest",
    "ListRepoFilesResponse",
    "PRData",
    "PRState",
    # Tool call envelope
    "ToolCallRequest",
    "ToolCallResponse",
    # Tool metadata
    "ToolDefinition",
    "ToolParameter",
    "UpdateIssueRequest",
    "UpdateIssueResponse",
]
