"""GitHub - Core Domain Models (SAP-042)

This module contains interface-agnostic Pydantic models for GitHub tool operations.
These models are shared across all interfaces (CLI, REST, MCP) following the
core/interface separation pattern.

Models follow the tool-calling pattern with:
- Request models for each tool (ListIssuesRequest, Create IssueRequest, etc.)
- Response models for each tool (ListIssuesResponse, CreateIssueResponse, etc.)
- Common data models (IssueData, PRData, FileData)
- Tool metadata models (ToolDefinition, ToolParameter)
- Tool call envelope (ToolCallRequest, ToolCallResponse)

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (8 tools)
"""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ============================================================================
# Base Models
# ============================================================================


class GithubBaseModel(BaseModel):
    """Base model for all GitHub domain models.

    Provides common configuration for domain entities.
    """

    model_config = {
        "json_schema_extra": {"examples": []},
        "populate_by_name": True,
        "use_enum_values": True,
    }


# ============================================================================
# Enums
# ============================================================================


class IssueState(str, Enum):
    """Issue state values."""

    OPEN = "open"
    CLOSED = "closed"
    ALL = "all"


class PRState(str, Enum):
    """Pull request state values."""

    OPEN = "open"
    CLOSED = "closed"
    ALL = "all"


class FileType(str, Enum):
    """File type values."""

    FILE = "file"
    DIR = "dir"
    SYMLINK = "symlink"


# ============================================================================
# Common Data Models
# ============================================================================


class IssueData(GithubBaseModel):
    """Issue data model used in responses."""

    number: int = Field(..., description="Issue number")
    title: str = Field(..., description="Issue title")
    state: str = Field(..., description="Issue state (open/closed)")
    url: str = Field(..., description="Issue URL")
    created_at: str = Field(..., description="Creation timestamp (ISO 8601)")
    updated_at: str | None = Field(
        None, description="Last update timestamp (ISO 8601)"
    )
    body: str | None = Field(None, description="Issue body/description")
    labels: list[str] = Field(default_factory=list, description="Issue labels")
    assignees: list[str] = Field(default_factory=list, description="Assigned users")
    author: str | None = Field(None, description="Issue author username")


class PRData(GithubBaseModel):
    """Pull request data model used in responses."""

    number: int = Field(..., description="PR number")
    title: str = Field(..., description="PR title")
    state: str = Field(..., description="PR state (open/closed/merged)")
    url: str = Field(..., description="PR URL")
    created_at: str = Field(..., description="Creation timestamp (ISO 8601)")
    updated_at: str | None = Field(
        None, description="Last update timestamp (ISO 8601)"
    )
    head_ref: str = Field(..., description="Source branch name")
    base_ref: str = Field(..., description="Target branch name")
    body: str | None = Field(None, description="PR description")
    author: str | None = Field(None, description="PR author username")
    mergeable: bool | None = Field(None, description="Whether PR can be merged")
    merged: bool | None = Field(None, description="Whether PR has been merged")


class FileData(GithubBaseModel):
    """File/directory data model used in responses."""

    name: str = Field(..., description="File/directory name")
    path: str = Field(..., description="Full path from repository root")
    type: str = Field(..., description="Type: file, dir, or symlink")
    size: int = Field(..., description="Size in bytes (0 for directories)")
    sha: str | None = Field(None, description="Git blob/tree SHA")


# ============================================================================
# Tool 1: list_issues
# ============================================================================


class ListIssuesRequest(GithubBaseModel):
    """Request model for list_issues tool."""

    repo: str = Field(
        ...,
        description="Repository in owner/repo format",
        examples=["anthropics/anthropic-sdk-python"],
    )
    state: IssueState = Field(default=IssueState.OPEN, description="Filter by state")
    labels: list[str] | None = Field(None, description="Filter by labels")
    assignee: str | None = Field(None, description="Filter by assignee")
    limit: int = Field(
        default=30, ge=1, le=100, description="Maximum results to return"
    )


class ListIssuesResponse(GithubBaseModel):
    """Response model for list_issues tool."""

    issues: list[IssueData] = Field(default_factory=list, description="List of issues")
    total_count: int = Field(..., ge=0, description="Total number of matching issues")


# ============================================================================
# Tool 2: create_issue
# ============================================================================


class CreateIssueRequest(GithubBaseModel):
    """Request model for create_issue tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    title: str = Field(..., min_length=1, max_length=256, description="Issue title")
    body: str = Field(..., description="Issue body/description")
    labels: list[str] | None = Field(None, description="Labels to apply")
    assignees: list[str] | None = Field(None, description="Users to assign")


class CreateIssueResponse(GithubBaseModel):
    """Response model for create_issue tool."""

    issue: IssueData = Field(..., description="Created issue")


# ============================================================================
# Tool 3: get_issue
# ============================================================================


class GetIssueRequest(GithubBaseModel):
    """Request model for get_issue tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    issue_number: int = Field(..., ge=1, description="Issue number")


class GetIssueResponse(GithubBaseModel):
    """Response model for get_issue tool."""

    issue: IssueData = Field(..., description="Issue details")


# ============================================================================
# Tool 4: update_issue
# ============================================================================


class UpdateIssueRequest(GithubBaseModel):
    """Request model for update_issue tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    issue_number: int = Field(..., ge=1, description="Issue number")
    title: str | None = Field(
        None, min_length=1, max_length=256, description="New title"
    )
    body: str | None = Field(None, description="New body/description")
    state: IssueState | None = Field(None, description="New state")
    labels: list[str] | None = Field(
        None, description="New labels (replaces existing)"
    )
    assignees: list[str] | None = Field(
        None, description="New assignees (replaces existing)"
    )


class UpdateIssueResponse(GithubBaseModel):
    """Response model for update_issue tool."""

    issue: IssueData = Field(..., description="Updated issue")


# ============================================================================
# Tool 5: list_prs
# ============================================================================


class ListPRsRequest(GithubBaseModel):
    """Request model for list_prs tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    state: PRState = Field(default=PRState.OPEN, description="Filter by state")
    head: str | None = Field(None, description="Filter by head branch")
    base: str | None = Field(None, description="Filter by base branch")
    limit: int = Field(
        default=30, ge=1, le=100, description="Maximum results to return"
    )


class ListPRsResponse(GithubBaseModel):
    """Response model for list_prs tool."""

    pull_requests: list[PRData] = Field(
        default_factory=list, description="List of pull requests"
    )
    total_count: int = Field(..., ge=0, description="Total number of matching PRs")


# ============================================================================
# Tool 6: get_pr
# ============================================================================


class GetPRRequest(GithubBaseModel):
    """Request model for get_pr tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    pr_number: int = Field(..., ge=1, description="Pull request number")


class GetPRResponse(GithubBaseModel):
    """Response model for get_pr tool."""

    pull_request: PRData = Field(..., description="Pull request details")


# ============================================================================
# Tool 7: get_file_contents
# ============================================================================


class GetFileContentsRequest(GithubBaseModel):
    """Request model for get_file_contents tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    path: str = Field(..., description="File path from repository root")
    ref: str = Field(default="main", description="Branch, tag, or commit SHA")


class GetFileContentsResponse(GithubBaseModel):
    """Response model for get_file_contents tool."""

    path: str = Field(..., description="File path")
    content: str = Field(..., description="File content (decoded)")
    size: int = Field(..., ge=0, description="File size in bytes")
    encoding: str = Field(default="utf-8", description="Content encoding")
    sha: str | None = Field(None, description="Git blob SHA")


# ============================================================================
# Tool 8: list_repo_files
# ============================================================================


class ListRepoFilesRequest(GithubBaseModel):
    """Request model for list_repo_files tool."""

    repo: str = Field(..., description="Repository in owner/repo format")
    path: str = Field(default="", description="Directory path (empty for root)")
    ref: str = Field(default="main", description="Branch, tag, or commit SHA")
    recursive: bool = Field(default=False, description="List recursively")


class ListRepoFilesResponse(GithubBaseModel):
    """Response model for list_repo_files tool."""

    files: list[FileData] = Field(
        default_factory=list, description="List of files/directories"
    )
    total_count: int = Field(..., ge=0, description="Total number of items")


# ============================================================================
# Tool Metadata Models (for /tools endpoint)
# ============================================================================


class ToolParameter(GithubBaseModel):
    """Tool parameter definition."""

    name: str = Field(..., description="Parameter name")
    type: str = Field(
        ..., description="Parameter type (string, integer, boolean, array, object)"
    )
    description: str = Field(..., description="Parameter description")
    required: bool = Field(default=False, description="Whether parameter is required")
    default: Any | None = Field(None, description="Default value if not required")
    enum: list[str] | None = Field(
        None, description="Allowed values (for string types)"
    )
    min_value: int | None = Field(
        None, description="Minimum value (for integer types)"
    )
    max_value: int | None = Field(
        None, description="Maximum value (for integer types)"
    )


class ToolDefinition(GithubBaseModel):
    """Tool definition metadata."""

    name: str = Field(..., description="Tool name (without namespace)")
    description: str = Field(..., description="Tool description")
    parameters: list[ToolParameter] = Field(
        default_factory=list, description="Tool parameters"
    )


# ============================================================================
# Tool Call Envelope (for /call endpoint)
# ============================================================================


class ToolCallRequest(GithubBaseModel):
    """Envelope for tool execution requests."""

    tool: str = Field(
        ..., description="Tool name (without namespace, e.g., 'list_issues')"
    )
    parameters: dict[str, Any] = Field(
        default_factory=dict, description="Tool parameters"
    )


class ToolCallResponse(GithubBaseModel):
    """Envelope for tool execution responses."""

    success: bool = Field(..., description="Whether the tool call succeeded")
    result: dict[str, Any] | None = Field(
        None, description="Tool result (if successful)"
    )
    error: str | None = Field(None, description="Error message (if failed)")
    error_code: str | None = Field(None, description="Error code (if failed)")
    warning: str | None = Field(None, description="Warning message (if applicable)")


# ============================================================================
# Example Usage (for documentation/testing)
# ============================================================================

if __name__ == "__main__":
    # Example: List issues
    list_req = ListIssuesRequest(
        repo="anthropics/anthropic-sdk-python", state=IssueState.OPEN
    )
    print(f"List Issues Request: {list_req.model_dump_json(indent=2)}")

    # Example: Create issue
    create_req = CreateIssueRequest(
        repo="owner/repo", title="Test Issue", body="Test body", labels=["bug"]
    )
    print(f"\nCreate Issue Request: {create_req.model_dump_json(indent=2)}")

    # Example: Tool call envelope
    tool_call = ToolCallRequest(
        tool="list_issues", parameters={"repo": "owner/repo", "state": "open"}
    )
    print(f"\nTool Call Request: {tool_call.model_dump_json(indent=2)}")

    # Example: Tool response
    tool_response = ToolCallResponse(
        success=True, result={"issues": [], "total_count": 0}
    )
    print(f"\nTool Call Response: {tool_response.model_dump_json(indent=2)}")
