"""GitHub - Core Business Logic Services (SAP-042)

This module contains interface-agnostic business logic that implements
the GitHub tool operations using PyGithub library.

The service layer:
- Accepts request models (ListIssuesRequest, CreateIssueRequest, etc.)
- Calls PyGithub to interact with GitHub API
- Returns response models (ListIssuesResponse, CreateIssueResponse, etc.)
- Handles errors and converts to custom exceptions

Generated by: chora-base SAP-047 (Capability Server Template)
Adapted for: GitHub Integration (8 tools)
"""


from github import Auth, Github, GithubException, UnknownObjectException

from .exceptions import (
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
)
from .models import (  # Request models; Response models; Data models
    CreateIssueRequest,
    CreateIssueResponse,
    FileData,
    GetFileContentsRequest,
    GetFileContentsResponse,
    GetIssueRequest,
    GetIssueResponse,
    GetPRRequest,
    GetPRResponse,
    IssueData,
    ListIssuesRequest,
    ListIssuesResponse,
    ListPRsRequest,
    ListPRsResponse,
    ListRepoFilesRequest,
    ListRepoFilesResponse,
    PRData,
    UpdateIssueRequest,
    UpdateIssueResponse,
)


class GithubToolService:
    """GitHub tool service implementing 8 GitHub operations.

    This service provides methods for each of the 8 GitHub tools:
    1. list_issues - List issues in a repository
    2. create_issue - Create a new issue
    3. get_issue - Get issue details
    4. update_issue - Update an existing issue
    5. list_prs - List pull requests
    6. get_pr - Get PR details
    7. get_file_contents - Read file contents
    8. list_repo_files - List files in a directory
    """

    def __init__(self, token: str):
        """Initialize service with GitHub token.

        Args:
            token: GitHub personal access token (PAT)

        Raises:
            ValueError: If token is None or empty
        """
        if not token or not token.strip():
            raise ValueError("GitHub token is required")

        self.token = token
        self.client = Github(auth=Auth.Token(token))

    def _convert_issue_to_data(self, issue) -> IssueData:
        """Convert PyGithub Issue to IssueData model.

        Args:
            issue: PyGithub Issue object

        Returns:
            IssueData model instance
        """
        return IssueData(
            number=issue.number,
            title=issue.title,
            state=issue.state,
            url=issue.html_url,
            created_at=issue.created_at.isoformat() if issue.created_at else None,
            updated_at=issue.updated_at.isoformat() if issue.updated_at else None,
            body=issue.body,
            labels=[label.name for label in issue.labels],
            assignees=[assignee.login for assignee in issue.assignees],
            author=issue.user.login if issue.user else None,
        )

    def _convert_pr_to_data(self, pr) -> PRData:
        """Convert PyGithub PullRequest to PRData model.

        Args:
            pr: PyGithub PullRequest object

        Returns:
            PRData model instance
        """
        return PRData(
            number=pr.number,
            title=pr.title,
            state=pr.state,
            url=pr.html_url,
            created_at=pr.created_at.isoformat() if pr.created_at else None,
            updated_at=pr.updated_at.isoformat() if pr.updated_at else None,
            head_ref=pr.head.ref,
            base_ref=pr.base.ref,
            body=pr.body,
            author=pr.user.login if pr.user else None,
            mergeable=pr.mergeable,
            merged=pr.merged,
        )

    def _convert_content_to_file_data(self, content) -> FileData:
        """Convert PyGithub ContentFile to FileData model.

        Args:
            content: PyGithub ContentFile object

        Returns:
            FileData model instance
        """
        return FileData(
            name=content.name,
            path=content.path,
            type=content.type,
            size=content.size,
            sha=content.sha,
        )

    def list_issues(self, request: ListIssuesRequest) -> ListIssuesResponse:
        """List issues in a repository.

        Args:
            request: ListIssuesRequest with repo, state, labels, assignee, limit

        Returns:
            ListIssuesResponse with issues and total count

        Raises:
            GithubNotFoundError: If repository not found
            GithubPermissionError: If access denied
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)

            # Build filter parameters
            kwargs = {"state": request.state}
            if request.labels:
                kwargs["labels"] = request.labels
            if request.assignee:
                kwargs["assignee"] = request.assignee

            # Get issues (paginated)
            issues_paginated = repo.get_issues(**kwargs)
            issues_list = list(issues_paginated[: request.limit])

            # Convert to data models
            issue_data = [self._convert_issue_to_data(issue) for issue in issues_list]

            return ListIssuesResponse(issues=issue_data, total_count=len(issue_data))

        except UnknownObjectException as e:
            raise GithubNotFoundError(f"Repository '{request.repo}' not found") from e
        except GithubException as e:
            if e.status == 403:
                raise GithubPermissionError(
                    f"Access denied to repository '{request.repo}'"
                ) from e
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def create_issue(self, request: CreateIssueRequest) -> CreateIssueResponse:
        """Create a new issue in a repository.

        Args:
            request: CreateIssueRequest with repo, title, body, labels, assignees

        Returns:
            CreateIssueResponse with created issue

        Raises:
            GithubNotFoundError: If repository not found
            GithubPermissionError: If access denied
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)

            # Create issue
            issue = repo.create_issue(
                title=request.title,
                body=request.body,
                labels=request.labels,
                assignees=request.assignees,
            )

            # Convert to data model
            issue_data = self._convert_issue_to_data(issue)

            return CreateIssueResponse(issue=issue_data)

        except UnknownObjectException as e:
            raise GithubNotFoundError(f"Repository '{request.repo}' not found") from e
        except GithubException as e:
            if e.status == 403:
                raise GithubPermissionError(
                    f"Access denied to repository '{request.repo}'"
                ) from e
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def get_issue(self, request: GetIssueRequest) -> GetIssueResponse:
        """Get details of a specific issue.

        Args:
            request: GetIssueRequest with repo and issue_number

        Returns:
            GetIssueResponse with issue details

        Raises:
            GithubNotFoundError: If repository or issue not found
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)
            issue = repo.get_issue(request.issue_number)

            # Convert to data model
            issue_data = self._convert_issue_to_data(issue)

            return GetIssueResponse(issue=issue_data)

        except UnknownObjectException as e:
            raise GithubNotFoundError(
                f"Issue #{request.issue_number} not found in '{request.repo}'"
            ) from e
        except GithubException as e:
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def update_issue(self, request: UpdateIssueRequest) -> UpdateIssueResponse:
        """Update an existing issue.

        Args:
            request: UpdateIssueRequest with repo, issue_number, and fields to update

        Returns:
            UpdateIssueResponse with updated issue

        Raises:
            GithubNotFoundError: If repository or issue not found
            GithubPermissionError: If access denied
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)
            issue = repo.get_issue(request.issue_number)

            # Build update parameters (only include non-None fields)
            kwargs = {}
            if request.title is not None:
                kwargs["title"] = request.title
            if request.body is not None:
                kwargs["body"] = request.body
            if request.state is not None:
                kwargs["state"] = request.state
            if request.labels is not None:
                kwargs["labels"] = request.labels
            if request.assignees is not None:
                kwargs["assignees"] = request.assignees

            # Update issue
            issue.edit(**kwargs)

            # Convert to data model (refresh to get updated data)
            issue_data = self._convert_issue_to_data(issue)

            return UpdateIssueResponse(issue=issue_data)

        except UnknownObjectException as e:
            raise GithubNotFoundError(
                f"Issue #{request.issue_number} not found in '{request.repo}'"
            ) from e
        except GithubException as e:
            if e.status == 403:
                raise GithubPermissionError(
                    f"Access denied to update issue in '{request.repo}'"
                ) from e
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def list_prs(self, request: ListPRsRequest) -> ListPRsResponse:
        """List pull requests in a repository.

        Args:
            request: ListPRsRequest with repo, state, head, base, limit

        Returns:
            ListPRsResponse with pull requests and total count

        Raises:
            GithubNotFoundError: If repository not found
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)

            # Build filter parameters
            kwargs = {"state": request.state}
            if request.head:
                kwargs["head"] = request.head
            if request.base:
                kwargs["base"] = request.base

            # Get pull requests (paginated)
            prs_paginated = repo.get_pulls(**kwargs)
            prs_list = list(prs_paginated[: request.limit])

            # Convert to data models
            pr_data = [self._convert_pr_to_data(pr) for pr in prs_list]

            return ListPRsResponse(pull_requests=pr_data, total_count=len(pr_data))

        except UnknownObjectException as e:
            raise GithubNotFoundError(f"Repository '{request.repo}' not found") from e
        except GithubException as e:
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def get_pr(self, request: GetPRRequest) -> GetPRResponse:
        """Get details of a specific pull request.

        Args:
            request: GetPRRequest with repo and pr_number

        Returns:
            GetPRResponse with PR details

        Raises:
            GithubNotFoundError: If repository or PR not found
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)
            pr = repo.get_pull(request.pr_number)

            # Convert to data model
            pr_data = self._convert_pr_to_data(pr)

            return GetPRResponse(pull_request=pr_data)

        except UnknownObjectException as e:
            raise GithubNotFoundError(
                f"PR #{request.pr_number} not found in '{request.repo}'"
            ) from e
        except GithubException as e:
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def get_file_contents(
        self, request: GetFileContentsRequest
    ) -> GetFileContentsResponse:
        """Read file contents from a repository.

        Args:
            request: GetFileContentsRequest with repo, path, ref

        Returns:
            GetFileContentsResponse with file content

        Raises:
            GithubNotFoundError: If repository or file not found
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)
            contents = repo.get_contents(request.path, ref=request.ref)

            # Decode content
            if hasattr(contents, "decoded_content"):
                content_str = contents.decoded_content.decode("utf-8")
            else:
                raise GithubError(f"'{request.path}' is not a file")

            return GetFileContentsResponse(
                path=contents.path,
                content=content_str,
                size=contents.size,
                encoding="utf-8",
                sha=contents.sha,
            )

        except UnknownObjectException as e:
            raise GithubNotFoundError(
                f"File '{request.path}' not found in '{request.repo}'"
            ) from e
        except UnicodeDecodeError as e:
            raise GithubError(f"File '{request.path}' is not UTF-8 encoded") from e
        except GithubException as e:
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e

    def list_repo_files(self, request: ListRepoFilesRequest) -> ListRepoFilesResponse:
        """List files in a repository directory.

        Args:
            request: ListRepoFilesRequest with repo, path, ref, recursive

        Returns:
            ListRepoFilesResponse with files and total count

        Raises:
            GithubNotFoundError: If repository or path not found
            GithubError: For other GitHub API errors
        """
        try:
            repo = self.client.get_repo(request.repo)

            # Get contents (can be a single file or list of files)
            contents = repo.get_contents(request.path, ref=request.ref)

            # Ensure we have a list
            if not isinstance(contents, list):
                contents = [contents]

            # Convert to data models
            file_data = [
                self._convert_content_to_file_data(content) for content in contents
            ]

            return ListRepoFilesResponse(files=file_data, total_count=len(file_data))

        except UnknownObjectException as e:
            raise GithubNotFoundError(
                f"Path '{request.path}' not found in '{request.repo}'"
            ) from e
        except GithubException as e:
            raise GithubError(
                f"GitHub API error: {e.data.get('message', str(e))}"
            ) from e
