"""GitHub - REST API Middleware (SAP-043)

Middleware for error handling, logging, and other cross-cutting concerns.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

import time
from collections.abc import Callable

from fastapi import Request, Response, status
from fastapi.responses import JSONResponse
from github.core import (
    GithubConfigError,
    GithubConflictError,
    GithubError,
    GithubNotFoundError,
    GithubPermissionError,
    GithubRateLimitError,
    GithubServiceError,
    GithubTimeoutError,
    GithubValidationError,
)


# ============================================================================
# Error Handler Middleware
# ============================================================================


async def error_handler_middleware(request: Request, call_next: Callable) -> Response:
    """Middleware to catch and format exceptions.

    Translates core domain exceptions to appropriate HTTP responses.

    Args:
        request: FastAPI request
        call_next: Next middleware/handler

    Returns:
        Response (possibly error response)
    """
    try:
        # Record start time for logging
        start_time = time.time()

        # Call next handler
        response = await call_next(request)

        # Log request duration
        duration = time.time() - start_time
        response.headers["X-Request-Duration"] = f"{duration:.3f}s"

        return response

    except GithubValidationError as e:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST, content=e.to_dict()
        )

    except GithubNotFoundError as e:
        return JSONResponse(status_code=status.HTTP_404_NOT_FOUND, content=e.to_dict())

    except GithubConflictError as e:
        return JSONResponse(status_code=status.HTTP_409_CONFLICT, content=e.to_dict())

    except GithubPermissionError as e:
        return JSONResponse(status_code=status.HTTP_403_FORBIDDEN, content=e.to_dict())

    except GithubRateLimitError as e:
        response = JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS, content=e.to_dict()
        )
        # Add Retry-After header if available
        if "retry_after_seconds" in e.details:
            response.headers["Retry-After"] = str(e.details["retry_after_seconds"])
        return response

    except GithubTimeoutError as e:
        return JSONResponse(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT, content=e.to_dict()
        )

    except GithubConfigError as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content=e.to_dict()
        )

    except GithubServiceError as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content=e.to_dict()
        )

    except GithubError as e:
        # Catch-all for other domain errors
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content=e.to_dict()
        )

    except Exception as e:
        # Unexpected errors
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={
                "error": "INTERNAL_ERROR",
                "message": "An unexpected error occurred",
                "details": {"type": type(e).__name__, "message": str(e)},
            },
        )
