"""GitHub - REST API Models (SAP-043)

API-specific request and response models. These are separate from core
models and may have different validation rules or fields suitable for
HTTP API interactions.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from typing import Any

from github.core import GithubEntity, GithubStatus
from pydantic import BaseModel, Field


# ============================================================================
# Request Models
# ============================================================================


class CreateEntityRequest(BaseModel):
    """Request model for creating an entity via API.

    This model may have different validation rules than the core
    GithubRequest model.
    """

    name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Entity name",
        examples=["My Entity"],
    )

    description: str | None = Field(
        None,
        max_length=2000,
        description="Optional description",
        examples=["A detailed description"],
    )

    metadata: dict[str, Any] | None = Field(
        None,
        description="Optional metadata as key-value pairs",
        examples=[{"priority": "high", "tags": "important"}],
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Important Task",
                "description": "This is an important task to complete",
                "metadata": {"priority": "high", "category": "development"},
            }
        }
    }


class UpdateEntityRequest(BaseModel):
    """Request model for updating an entity via API.

    For PATCH requests, all fields are optional. For PUT requests,
    all fields should be provided.
    """

    name: str | None = Field(
        None, min_length=1, max_length=200, description="Entity name"
    )

    description: str | None = Field(None, max_length=2000, description="Description")

    metadata: dict[str, Any] | None = Field(
        None, description="Metadata as key-value pairs"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Updated Task Name",
                "description": "Updated description",
                "metadata": {"priority": "low"},
            }
        }
    }


class UpdateStatusRequest(BaseModel):
    """Request model for updating entity status."""

    status: GithubStatus = Field(..., description="New status value")

    model_config = {"json_schema_extra": {"example": {"status": "active"}}}


# ============================================================================
# Response Models
# ============================================================================


class EntityResponse(BaseModel):
    """Response model for single entity operations."""

    success: bool = Field(True, description="Whether the operation succeeded")

    message: str | None = Field(None, description="Optional response message")

    entity: GithubEntity = Field(..., description="The entity")

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "message": "Entity created successfully",
                "entity": {
                    "id": "123e4567-e89b-12d3-a456-426614174000",
                    "name": "Example Entity",
                    "description": "Description",
                    "status": "pending",
                    "metadata": {},
                    "created_at": "2025-01-15T10:30:00Z",
                    "updated_at": "2025-01-15T10:30:00Z",
                },
            }
        }
    }


class EntityListResponse(BaseModel):
    """Response model for entity list operations."""

    entities: list[GithubEntity] = Field(
        default_factory=list, description="List of entities"
    )

    total: int = Field(0, ge=0, description="Total number of entities matching filters")

    offset: int = Field(0, ge=0, description="Pagination offset")

    limit: int = Field(
        100, ge=1, le=1000, description="Maximum number of entities returned"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "entities": [
                    {
                        "id": "123e4567-e89b-12d3-a456-426614174000",
                        "name": "Entity 1",
                        "status": "active",
                        "created_at": "2025-01-15T10:30:00Z",
                    }
                ],
                "total": 10,
                "offset": 0,
                "limit": 100,
            }
        }
    }


class ErrorResponse(BaseModel):
    """Response model for error responses.

    This matches the structure of core exception.to_dict() output.
    """

    error: str = Field(..., description="Machine-readable error code")

    message: str = Field(..., description="Human-readable error message")

    details: dict[str, Any] = Field(
        default_factory=dict, description="Additional error details"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "error": "VALIDATION_ERROR",
                "message": "Invalid input data",
                "details": {"field": "name", "value": ""},
            }
        }
    }


class HealthResponse(BaseModel):
    """Response model for health check."""

    status: str = Field(..., description="Health status (healthy, degraded, unhealthy)")

    entity_count: int = Field(0, ge=0, description="Number of entities in storage")

    timestamp: str = Field(..., description="Timestamp of health check (ISO 8601)")

    model_config = {
        "json_schema_extra": {
            "example": {
                "status": "healthy",
                "entity_count": 42,
                "timestamp": "2025-01-15T10:30:00Z",
            }
        }
    }
