"""GitHub - REST API Routes (SAP-043)

API endpoint definitions. Routes translate HTTP requests to core service
calls and format responses.

Generated by: chora-base SAP-047 (Capability Server Template)
"""

from uuid import UUID

from fastapi import APIRouter, Query
from fastapi import status as http_status
from github.core import (
    GithubEntity,
    GithubFilter,
    GithubRequest,
    GithubStatus,
    create_github_service,
)

from .models import (
    CreateEntityRequest,
    EntityListResponse,
    EntityResponse,
    UpdateEntityRequest,
    UpdateStatusRequest,
)


# ============================================================================
# Router Setup
# ============================================================================


router = APIRouter(prefix="/github", tags=["GitHub"])


# ============================================================================
# Dependency: Service Instance
# ============================================================================


def get_service():
    """Get service instance.

    This is a dependency that can be overridden for testing.
    """
    return create_github_service()


# ============================================================================
# Create Entity
# ============================================================================


@router.post(
    "/entities",
    response_model=EntityResponse,
    status_code=http_status.HTTP_201_CREATED,
    summary="Create new entity",
    description="Create a new github entity with the provided data.",
)
async def create_entity(request: CreateEntityRequest) -> EntityResponse:
    """Create a new entity.

    Args:
        request: Entity creation request

    Returns:
        Created entity

    Raises:
        400: Validation error
        500: Internal server error
    """
    service = get_service()

    # Convert API request to core request
    core_request = GithubRequest(
        name=request.name,
        description=request.description,
        metadata=request.metadata or {},
    )

    # Call core service
    response = await service.create(core_request)

    # Convert to API response
    return EntityResponse(
        success=response.success, message=response.message, entity=response.entity
    )


# ============================================================================
# Get Entity
# ============================================================================


@router.get(
    "/entities/{entity_id}",
    response_model=GithubEntity,
    summary="Get entity by ID",
    description="Retrieve a github entity by its unique identifier.",
)
async def get_entity(entity_id: UUID) -> GithubEntity:
    """Get entity by ID.

    Args:
        entity_id: Entity unique identifier

    Returns:
        The entity

    Raises:
        404: Entity not found
        500: Internal server error
    """
    service = get_service()
    return await service.get(entity_id)


# ============================================================================
# List Entities
# ============================================================================


@router.get(
    "/entities",
    response_model=EntityListResponse,
    summary="List entities",
    description="List github entities with optional filtering and pagination.",
)
async def list_entities(
    status: GithubStatus | None = Query(None, description="Filter by status"),
    name_contains: str | None = Query(
        None, description="Filter by name containing text (case-insensitive)"
    ),
    offset: int = Query(0, ge=0, description="Pagination offset"),
    limit: int = Query(100, ge=1, le=1000, description="Maximum number of results"),
) -> EntityListResponse:
    """List entities with optional filtering.

    Args:
        status: Optional status filter
        name_contains: Optional name search filter
        offset: Pagination offset (default: 0)
        limit: Maximum results (default: 100, max: 1000)

    Returns:
        List of entities with pagination metadata

    Raises:
        400: Invalid filter parameters
        500: Internal server error
    """
    service = get_service()

    # Build filter
    filters = GithubFilter(
        status=status, name_contains=name_contains, offset=offset, limit=limit
    )

    # Call core service
    response = await service.list(filters)

    # Convert to API response
    return EntityListResponse(
        entities=response.entities,
        total=response.total,
        offset=response.offset,
        limit=response.limit,
    )


# ============================================================================
# Update Entity
# ============================================================================


@router.put(
    "/entities/{entity_id}",
    response_model=EntityResponse,
    summary="Update entity",
    description="Update an existing github entity.",
)
async def update_entity(
    entity_id: UUID, request: UpdateEntityRequest
) -> EntityResponse:
    """Update an existing entity.

    Args:
        entity_id: Entity to update
        request: Update request

    Returns:
        Updated entity

    Raises:
        400: Validation error
        404: Entity not found
        500: Internal server error
    """
    service = get_service()

    # Convert API request to core request
    core_request = GithubRequest(
        name=request.name,
        description=request.description,
        metadata=request.metadata or {},
    )

    # Call core service
    response = await service.update(entity_id, core_request)

    # Convert to API response
    return EntityResponse(
        success=response.success, message=response.message, entity=response.entity
    )


# ============================================================================
# Partial Update Entity (PATCH)
# ============================================================================


@router.patch(
    "/entities/{entity_id}",
    response_model=EntityResponse,
    summary="Partially update entity",
    description="Update specific fields of an existing github entity.",
)
async def patch_entity(entity_id: UUID, request: UpdateEntityRequest) -> EntityResponse:
    """Partially update an entity.

    Only provided fields will be updated. Omitted fields remain unchanged.

    Args:
        entity_id: Entity to update
        request: Partial update request

    Returns:
        Updated entity

    Raises:
        400: Validation error
        404: Entity not found
        500: Internal server error
    """
    service = get_service()

    # Get existing entity
    existing = await service.get(entity_id)

    # Merge with existing values
    core_request = GithubRequest(
        name=request.name if request.name else existing.name,
        description=(
            request.description
            if request.description is not None
            else existing.description
        ),
        metadata=(
            request.metadata if request.metadata is not None else existing.metadata
        ),
    )

    # Call core service
    response = await service.update(entity_id, core_request)

    # Convert to API response
    return EntityResponse(
        success=response.success, message=response.message, entity=response.entity
    )


# ============================================================================
# Delete Entity
# ============================================================================


@router.delete(
    "/entities/{entity_id}",
    status_code=http_status.HTTP_204_NO_CONTENT,
    summary="Delete entity",
    description="Delete a github entity.",
)
async def delete_entity(entity_id: UUID):
    """Delete an entity.

    Args:
        entity_id: Entity to delete

    Returns:
        None (204 No Content)

    Raises:
        404: Entity not found
        500: Internal server error
    """
    service = get_service()
    await service.delete(entity_id)


# ============================================================================
# Update Status
# ============================================================================


@router.post(
    "/entities/{entity_id}/status",
    response_model=EntityResponse,
    summary="Update entity status",
    description="Update the status of a github entity.",
)
async def update_status(
    entity_id: UUID, request: UpdateStatusRequest
) -> EntityResponse:
    """Update entity status.

    Args:
        entity_id: Entity to update
        request: Status update request

    Returns:
        Updated entity

    Raises:
        400: Invalid status transition
        404: Entity not found
        500: Internal server error
    """
    service = get_service()

    # Call core service
    response = await service.update_status(entity_id, request.status)

    # Convert to API response
    return EntityResponse(
        success=response.success, message=response.message, entity=response.entity
    )


# ============================================================================
# Bulk Operations (Optional)
# ============================================================================


@router.post(
    "/entities/bulk/delete",
    status_code=http_status.HTTP_200_OK,
    summary="Bulk delete entities",
    description="Delete multiple entities at once.",
)
async def bulk_delete(entity_ids: list[UUID]) -> dict:
    """Bulk delete entities.

    Args:
        entity_ids: List of entity IDs to delete

    Returns:
        Summary of deletion results

    Raises:
        500: Internal server error
    """
    service = get_service()

    deleted = []
    failed = []

    for entity_id in entity_ids:
        try:
            await service.delete(entity_id)
            deleted.append(str(entity_id))
        except Exception as e:
            failed.append({"id": str(entity_id), "error": str(e)})

    return {
        "deleted_count": len(deleted),
        "failed_count": len(failed),
        "deleted": deleted,
        "failed": failed,
    }
